export type Keys =
  | "LButton" // 鼠标左键
  | "RButton" // 鼠标右键
  | "Cancel" // 取消/中断键
  | "MButton" // 鼠标中键
  | "XButton1" // 鼠标侧键1（前进键）
  | "XButton2" // 鼠标侧键2（后退键）
  | "Back" // 退格键
  | "Tab" // 制表键
  | "LineFeed" // 换行键
  | "Clear" // 清除键
  | "Return" // 回车键
  | "Enter" // 回车键（与Return同义）
  | "ShiftKey" // Shift键
  | "ControlKey" // Ctrl键
  | "Menu" // Alt键（也称为菜单键）
  | "Pause" // 暂停键
  | "Capital" // 大写锁定键
  | "CapsLock" // 大写锁定键（同Capital）
  | "KanaMode" // 日文假名输入模式
  | "HanguelMode" // 韩文Hanguel输入模式（已过时，建议使用HangulMode）
  | "HangulMode" // 韩文Hangul输入模式
  | "JunjaMode" // 韩文Junja输入模式
  | "FinalMode" // 输入法最终模式
  | "HanjaMode" // 韩文汉字输入模式
  | "KanjiMode" // 日文汉字输入模式
  | "Escape" // Esc键
  | "IMEConvert" // IME转换键
  | "IMENonconvert" // IME非转换键
  | "IMEAccept" // IME接受键
  | "IMEAceept" // IME接受键（过时拼写，建议使用IMEAccept）
  | "IMEModeChange" // IME模式切换键
  | "Space" // 空格键
  | "Prior" // Page Up键
  | "PageUp" // Page Up键（同Prior）
  | "Next" // Page Down键
  | "PageDown" // Page Down键（同Next）
  | "End" // End键
  | "Home" // Home键
  | "Left" // 向左箭头键
  | "Up" // 向上箭头键
  | "Right" // 向右箭头键
  | "Down" // 向下箭头键
  | "Select" // 选择键
  | "Print" // 打印键
  | "Execute" // 执行键
  | "Snapshot" // 截图键
  | "PrintScreen" // 打印屏幕键（同Snapshot）
  | "Insert" // Insert键
  | "Delete" // Delete键
  | "Help" // 帮助键
  | "D0" // 主键盘数字0键
  | "D1" // 主键盘数字1键
  | "D2" // 主键盘数字2键
  | "D3" // 主键盘数字3键
  | "D4" // 主键盘数字4键
  | "D5" // 主键盘数字5键
  | "D6" // 主键盘数字6键
  | "D7" // 主键盘数字7键
  | "D8" // 主键盘数字8键
  | "D9" // 主键盘数字9键
  | "A" // A键
  | "B" // B键
  | "C" // C键
  | "D" // D键
  | "E" // E键
  | "F" // F键
  | "G" // G键
  | "H" // H键
  | "I" // I键
  | "J" // J键
  | "K" // K键
  | "L" // L键
  | "M" // M键
  | "N" // N键
  | "O" // O键
  | "P" // P键
  | "Q" // Q键
  | "R" // R键
  | "S" // S键
  | "T" // T键
  | "U" // U键
  | "V" // V键
  | "W" // W键
  | "X" // X键
  | "Y" // Y键
  | "Z" // Z键
  | "LWin" // 左侧Windows徽标键
  | "RWin" // 右侧Windows徽标键
  | "Apps" // 应用程序键（右键菜单键）
  | "Sleep" // 休眠键
  | "NumPad0" // 小键盘数字0键
  | "NumPad1" // 小键盘数字1键
  | "NumPad2" // 小键盘数字2键
  | "NumPad3" // 小键盘数字3键
  | "NumPad4" // 小键盘数字4键
  | "NumPad5" // 小键盘数字5键
  | "NumPad6" // 小键盘数字6键
  | "NumPad7" // 小键盘数字7键
  | "NumPad8" // 小键盘数字8键
  | "NumPad9" // 小键盘数字9键
  | "Multiply" // 小键盘乘号键（*）
  | "Add" // 小键盘加号键（+）
  | "Separator" // 分隔符键
  | "Subtract" // 小键盘减号键（-）
  | "Decimal" // 小键盘小数点键（.）
  | "Divide" // 小键盘除号键（/）
  | "F1" // F1功能键
  | "F2" // F2功能键
  | "F3" // F3功能键
  | "F4" // F4功能键
  | "F5" // F5功能键
  | "F6" // F6功能键
  | "F7" // F7功能键
  | "F8" // F8功能键
  | "F9" // F9功能键
  | "F10" // F10功能键
  | "F11" // F11功能键
  | "F12" // F12功能键
  | "F13" // F13功能键
  | "F14" // F14功能键
  | "F15" // F15功能键
  | "F16" // F16功能键
  | "F17" // F17功能键
  | "F18" // F18功能键
  | "F19" // F19功能键
  | "F20" // F20功能键
  | "F21" // F21功能键
  | "F22" // F22功能键
  | "F23" // F23功能键
  | "F24" // F24功能键
  | "NumLock" // 数字锁定键
  | "Scroll" // 滚动锁定键
  | "LShiftKey" // 左侧Shift键
  | "RShiftKey" // 右侧Shift键
  | "LControlKey" // 左侧Ctrl键
  | "RControlKey" // 右侧Ctrl键
  | "LMenu" // 左侧Alt键
  | "RMenu" // 右侧Alt键
  | "BrowserBack" // 浏览器后退键
  | "BrowserForward" // 浏览器前进键
  | "BrowserRefresh" // 浏览器刷新键
  | "BrowserStop" // 浏览器停止键
  | "BrowserSearch" // 浏览器搜索键
  | "BrowserFavorites" // 浏览器收藏夹键
  | "BrowserHome" // 浏览器主页键
  | "VolumeMute" // 音量静音键
  | "VolumeDown" // 音量降低键
  | "VolumeUp" // 音量提高键
  | "MediaNextTrack" // 媒体下一曲键
  | "MediaPreviousTrack" // 媒体上一曲键
  | "MediaStop" // 媒体停止键
  | "MediaPlayPause" // 媒体播放/暂停键
  | "LaunchMail" // 启动邮件客户端键
  | "SelectMedia" // 选择媒体键
  | "LaunchApplication1" // 启动应用程序1键
  | "LaunchApplication2" // 启动应用程序2键
  | "OemSemicolon" // OEM分号键（;）
  | "Oem1" // OEM键1（同OemSemicolon）
  | "Oemplus" // OEM加号键（+）
  | "Oemcomma" // OEM逗号键（,）
  | "OemMinus" // OEM减号键（-）
  | "OemPeriod" // OEM句号键（.）
  | "OemQuestion" // OEM问号键（?）
  | "Oem2" // OEM键2（同OemQuestion）
  | "Oemtilde" // OEM波浪线键（~）
  | "Oem3" // OEM键3（同Oemtilde）
  | "OemOpenBrackets" // OEM左方括号键（[）
  | "Oem4" // OEM键4（同OemOpenBrackets）
  | "OemPipe" // OEM竖线键（|）
  | "Oem5" // OEM键5（同OemPipe）
  | "OemCloseBrackets" // OEM右方括号键（]）
  | "Oem6" // OEM键6（同OemCloseBrackets）
  | "OemQuotes" // OEM引号键（'）
  | "Oem7" // OEM键7（同OemQuotes）
  | "Oem8" // OEM键8
  | "OemBackslash" // OEM反斜杠键（\）
  | "Oem102" // OEM102键（通常为\或|，根据键盘布局）
  | "ProcessKey" // 处理键
  | "Packet" // 数据包键（用于Unicode字符输入）
  | "Attn" // 注意键
  | "Crsel" // 光标选择键
  | "Exsel" // 扩展选择键
  | "EraseEof" // 删除至文件末尾键
  | "Play" // 播放键
  | "Zoom" // 缩放键
  | "NoName" // 未命名键（保留供未来使用）
  | "Pa1" // PA1键
  | "OemClear" // OEM清除键
  | "Shift" // Shift修饰键
  | "Control" // Ctrl修饰键
  | "Alt"; // Alt修饰键

export type KeyCodeString = Keys;

/**
 * 组合键的字符串表示是逆序的，即 "A, Control" 表示 "Control + A"。
 * 为了在类型安全性和性能之间取得平衡，这里仅支持最多两个按键的组合，超过两个按键的组合将回退到通用的字符串类型。
 */
export type KeyDataString = Keys | `${Keys}, ${Keys}` | (string & {});
