export type Key =
  | "LBUTTON" // 鼠标左键
  | "RBUTTON" // 鼠标右键
  | "CANCEL" // 取消/中断键
  | "MBUTTON" // 鼠标中键
  | "XBUTTON1" // 鼠标侧键1（前进键）
  | "XBUTTON2" // 鼠标侧键2（后退键）
  | "BACK" // 退格键
  | "TAB" // 制表键
  | "CLEAR" // 清除键
  | "RETURN" // 回车键
  | "SHIFT" // Shift键（不区分左右）
  | "LSHIFT" // 左侧Shift键
  | "RSHIFT" // 右侧Shift键
  | "CONTROL" // Ctrl键（不区分左右）
  | "LCONTROL" // 左侧Ctrl键
  | "RCONTROL" // 右侧Ctrl键
  | "MENU" // Alt键（不区分左右）
  | "LMENU" // 左侧Alt键
  | "RMENU" // 右侧Alt键
  | "PAUSE" // 暂停键
  | "CAPITAL" // 大写锁定键
  | "KANA" // 日文假名输入模式
  | "HANGUL" // 韩文Hangul输入模式
  | "HANGUEL" // 韩文Hanguel输入模式（同Hangul）
  | "IME_ON" // 输入法开启状态
  | "JUNJA" // 韩文Junja输入模式
  | "FINAL" // 输入法最终模式
  | "HANJA" // 韩文汉字输入模式
  | "KANJI" // 日文汉字输入模式
  | "IME_OFF" // 输入法关闭状态
  | "ESCAPE" // Esc键
  | "CONVERT" // 输入法转换键
  | "NONCONVERT" // 输入法非转换键
  | "ACCEPT" // 输入法接受键
  | "MODECHANGE" // 输入法模式切换键
  | "SPACE" // 空格键
  | "PRIOR" // Page Up键
  | "NEXT" // Page Down键
  | "END" // End键
  | "HOME" // Home键
  | "UP" // 向上方向键
  | "DOWN" // 向下方向键
  | "LEFT" // 向左方向键
  | "RIGHT" // 向右方向键
  | "SELECT" // 选择键
  | "PRINT" // 打印键
  | "EXECUTE" // 执行键
  | "SNAPSHOT" // 截图键（同Print）
  | "INSERT" // Insert键
  | "DELETE" // Delete键
  | "HELP" // 帮助键
  | "0" // 主键盘数字0键
  | "1" // 主键盘数字1键
  | "2" // 主键盘数字2键
  | "3" // 主键盘数字3键
  | "4" // 主键盘数字4键
  | "5" // 主键盘数字5键
  | "6" // 主键盘数字6键
  | "7" // 主键盘数字7键
  | "8" // 主键盘数字8键
  | "9" // 主键盘数字9键
  | "A" // A键
  | "B" // B键
  | "C" // C键
  | "D" // D键
  | "E" // E键
  | "F" // F键
  | "G" // G键
  | "H" // H键
  | "I" // I键
  | "J" // J键
  | "K" // K键
  | "L" // L键
  | "M" // M键
  | "N" // N键
  | "O" // O键
  | "P" // P键
  | "Q" // Q键
  | "R" // R键
  | "S" // S键
  | "T" // T键
  | "U" // U键
  | "V" // V键
  | "W" // W键
  | "X" // X键
  | "Y" // Y键
  | "Z" // Z键
  | "LWIN" // 左侧Windows徽标键
  | "RWIN" // 右侧Windows徽标键
  | "APPS" // 应用程序键（右键菜单键）
  | "SLEEP" // 休眠键
  | "NUMPAD0" // 小键盘数字0键
  | "NUMPAD1" // 小键盘数字1键
  | "NUMPAD2" // 小键盘数字2键
  | "NUMPAD3" // 小键盘数字3键
  | "NUMPAD4" // 小键盘数字4键
  | "NUMPAD5" // 小键盘数字5键
  | "NUMPAD6" // 小键盘数字6键
  | "NUMPAD7" // 小键盘数字7键
  | "NUMPAD8" // 小键盘数字8键
  | "NUMPAD9" // 小键盘数字9键
  | "MULTIPLY" // 小键盘乘号键（*）
  | "ADD" // 小键盘加号键（+）
  | "SEPARATOR" // 分隔符键
  | "SUBTRACT" // 小键盘减号键（-）
  | "DECIMAL" // 小键盘小数点键（.）
  | "DIVIDE" // 小键盘除号键（/）
  | "F1" // F1功能键
  | "F2" // F2功能键
  | "F3" // F3功能键
  | "F4" // F4功能键
  | "F5" // F5功能键
  | "F6" // F6功能键
  | "F7" // F7功能键
  | "F8" // F8功能键
  | "F9" // F9功能键
  | "F10" // F10功能键
  | "F11" // F11功能键
  | "F12" // F12功能键
  | "F13" // F13功能键
  | "F14" // F14功能键
  | "F15" // F15功能键
  | "F16" // F16功能键
  | "F17" // F17功能键
  | "F18" // F18功能键
  | "F19" // F19功能键
  | "F20" // F20功能键
  | "F21" // F21功能键
  | "F22" // F22功能键
  | "F23" // F23功能键
  | "F24" // F24功能键
  | "NUMLOCK" // 数字锁定键
  | "SCROLL" // 滚动锁定键
  | "BROWSER_BACK" // 浏览器后退键
  | "BROWSER_FORWARD" // 浏览器前进键
  | "BROWSER_REFRESH" // 浏览器刷新键
  | "BROWSER_STOP" // 浏览器停止键
  | "BROWSER_SEARCH" // 浏览器搜索键
  | "BROWSER_FAVORITES" // 浏览器收藏夹键
  | "BROWSER_HOME" // 浏览器主页键
  | "VOLUME_MUTE" // 音量静音键
  | "VOLUME_DOWN" // 音量降低键
  | "VOLUME_UP" // 音量提高键
  | "MEDIA_NEXT_TRACK" // 媒体下一曲键
  | "MEDIA_PREV_TRACK" // 媒体上一曲键
  | "MEDIA_STOP" // 媒体停止键
  | "MEDIA_PLAY_PAUSE" // 媒体播放/暂停键
  | "LAUNCH_MAIL" // 启动邮件客户端键
  | "LAUNCH_MEDIA_SELECT" // 选择媒体键
  | "LAUNCH_APP1" // 启动应用程序1键
  | "LAUNCH_APP2" // 启动应用程序2键
  | "OEM_1" // OEM分号键（;）
  | "OEM_PLUS" // OEM加号键（+）
  | "OEM_COMMA" // OEM逗号键（,）
  | "OEM_MINUS" // OEM减号键（-）
  | "OEM_PERIOD" // OEM句号键（.）
  | "OEM_2" // OEM问号键（?）
  | "OEM_3" // OEM波浪线键（~）
  | "OEM_4" // OEM左方括号键（[）
  | "OEM_5" // OEM竖线键（|）
  | "OEM_6" // OEM右方括号键（]）
  | "OEM_7" // OEM引号键（'）
  | "OEM_8" // OEM键8
  | "OEM_NEC_EQUAL" // NEC等号键（小键盘）
  | "OEM_FJ_JISHO" // 富士通"辞书"键
  | "OEM_FJ_MASSHOU" // 富士通"未登録"键
  | "OEM_FJ_TOUROKU" // 富士通"登録"键
  | "OEM_FJ_LOYA" // 富士通左Oyayubi键
  | "OEM_FJ_ROYA" // 富士通右Oyayubi键
  | "OEM_AX" // AX键（日语键盘）
  | "OEM_102" // OEM102键（通常为\或|，根据键盘布局）
  | "OEM_RESET" // OEM重置键（Nokia/Ericsson定义）
  | "OEM_JUMP" // OEM跳转键（Nokia/Ericsson定义）
  | "OEM_PA1" // OEM PA1键（Nokia/Ericsson定义）
  | "OEM_PA2" // OEM PA2键（Nokia/Ericsson定义）
  | "OEM_PA3" // OEM PA3键（Nokia/Ericsson定义）
  | "OEM_WSCTRL" // OEM WSCTRL键（Nokia/Ericsson定义）
  | "OEM_CUSEL" // OEM CUSEL键（Nokia/Ericsson定义）
  | "OEM_ATTN" // OEM ATTN键（Nokia/Ericsson定义）
  | "OEM_FINISH" // OEM FINISH键（Nokia/Ericsson定义）
  | "OEM_COPY" // OEM COPY键（Nokia/Ericsson定义）
  | "OEM_AUTO" // OEM AUTO键（Nokia/Ericsson定义）
  | "OEM_ENLW" // OEM ENLW键（Nokia/Ericsson定义）
  | "OEM_BACKTAB" // OEM BackTab键（Nokia/Ericsson定义）
  | "GAMEPAD_A" // 游戏手柄A键
  | "GAMEPAD_B" // 游戏手柄B键
  | "GAMEPAD_X" // 游戏手柄X键
  | "GAMEPAD_Y" // 游戏手柄Y键
  | "GAMEPAD_LEFT_SHOULDER" // 游戏手柄左肩键
  | "GAMEPAD_RIGHT_SHOULDER" // 游戏手柄右肩键
  | "GAMEPAD_LEFT_TRIGGER" // 游戏手柄左扳机键
  | "GAMEPAD_RIGHT_TRIGGER" // 游戏手柄右扳机键
  | "GAMEPAD_DPAD_UP" // 游戏手柄方向键上
  | "GAMEPAD_DPAD_DOWN" // 游戏手柄方向键下
  | "GAMEPAD_DPAD_LEFT" // 游戏手柄方向键左
  | "GAMEPAD_DPAD_RIGHT" // 游戏手柄方向键右
  | "GAMEPAD_MENU" // 游戏手柄菜单键
  | "GAMEPAD_VIEW" // 游戏手柄视图键
  | "GAMEPAD_LEFT_THUMBSTICK_BUTTON" // 游戏手柄左摇杆按钮
  | "GAMEPAD_RIGHT_THUMBSTICK_BUTTON" // 游戏手柄右摇杆按钮
  | "GAMEPAD_LEFT_THUMBSTICK_UP" // 游戏手柄左摇杆上推
  | "GAMEPAD_LEFT_THUMBSTICK_DOWN" // 游戏手柄左摇杆下推
  | "GAMEPAD_LEFT_THUMBSTICK_LEFT" // 游戏手柄左摇杆左推
  | "GAMEPAD_LEFT_THUMBSTICK_RIGHT" // 游戏手柄左摇杆右推
  | "GAMEPAD_RIGHT_THUMBSTICK_UP" // 游戏手柄右摇杆上推
  | "GAMEPAD_RIGHT_THUMBSTICK_DOWN" // 游戏手柄右摇杆下推
  | "GAMEPAD_RIGHT_THUMBSTICK_LEFT" // 游戏手柄右摇杆左推
  | "GAMEPAD_RIGHT_THUMBSTICK_RIGHT" // 游戏手柄右摇杆右推
  | "PROCESSKEY" // IME处理键
  | "ICO_CLEAR" // ICO清除键
  | "PACKET" // 数据包键（用于Unicode字符输入）
  | "ATTN" // 注意键
  | "CRSEL" // 光标选择键
  | "EXSEL" // 扩展选择键
  | "EREOF" // 删除至文件末尾键
  | "PLAY" // 播放键
  | "ZOOM" // 缩放键
  | "NONAME" // 未命名键（保留供未来使用）
  | "PA1" // PA1键
  | "OEM_CLEAR"; // OEM清除键

export type KeyCode =
  | Uppercase<Key>
  | Lowercase<Key>
  | Uppercase<`VK_${Key}`>
  | Lowercase<`VK_${Key}`>;
