import path from "node:path";
import glob from "tiny-glob";
import { type ScriptConfig } from "../config.js";

export const parseBuildConfig = async (config: ScriptConfig, pkg: any) => {
  // 脚本入口文件
  const main = [config.main || "main.ts"];

  // 资源文件目录
  const assetsDir = config.assetsDir || "assets";

  // 构建输出路径
  const outDir = path.resolve(config.outDir || "dist");

  // 额外打包文件
  const files = Array.isArray(config.additionalFiles)
    ? config.additionalFiles
    : config.additionalFiles
      ? [config.additionalFiles]
      : ["README.md", "LICENSE"];
  const copies = files.map(async item => {
    if (typeof item === "string") {
      const filePaths = await glob(item, { cwd: path.resolve("."), absolute: true });
      return filePaths.map(filePath => ({
        from: filePath,
        to: path.resolve(outDir, path.basename(filePath))
      }));
    }
    if (typeof item === "object") {
      return [
        {
          from: path.resolve(item.from),
          to: path.resolve(outDir, item.to ? item.to : path.basename(item.from))
        }
      ];
    }
    return [];
  });
  const additionalFiles = (await Promise.all(copies)).flat();

  // 加载器配置
  const loaders = {
    image: {
      baseDir: config.loaders?.image?.baseDir || "assets"
    }
  };

  // 启用脚本压缩
  const minify = config.minify ?? false;

  // 文件头部注释
  const defaultBanner = `/**
 * Better Genshin Impact JavaScript
 * Bundled with BetterGI CLI (https://www.npmjs.com/package/@bettergi/cli)
 * 
 * This file is automatically generated and should not be edited.
 */`;
  const banner =
    config.banner === false
      ? ""
      : typeof config.banner === "string"
        ? config.banner
        : defaultBanner;

  // 监听文件变化（支持通配符）
  const watch = config.watch || [];

  return { main, assetsDir, outDir, additionalFiles, loaders, minify, banner, watch };
};
