import path from "node:path";
import { type BuildOptions, type OutputOptions } from "rolldown";
import glob from "tiny-glob";
import { lookupPackageInfo } from "../utils/pkg.js";
import { type ConfigContext } from "./index.js";

type Context = Pick<ConfigContext, "config" | "configFile" | "pkg">;

export interface BuildConfig {
  main: string;
  assetsDir: string;
  outDir: string;
  additionalFiles: {
    from: string;
    to: string;
  }[];
  loaders: {
    image: {
      baseDir: string;
    };
  };
  codeSplitting: boolean;
  advancedChunks: OutputOptions["advancedChunks"];
  treeshake: BuildOptions["treeshake"];
  minify: boolean;
  banner: string;
  watch: string[];
}

export const parseBuildConfig = async (context: Context): Promise<BuildConfig> => {
  const { config, configFile } = context;

  // 脚本入口文件
  const main = config.main || "main.ts";

  // 资源文件目录
  const assetsDir = config.assetsDir || "assets";

  // 构建输出路径
  const outDir = path.resolve(config.outDir || "dist");

  // 额外打包文件
  const files = Array.isArray(config.additionalFiles)
    ? config.additionalFiles
    : config.additionalFiles
      ? [config.additionalFiles]
      : ["README.md", "LICENSE"];
  const copies = files.map(async item => {
    if (typeof item === "string") {
      const filePaths = await glob(item, { cwd: path.resolve("."), absolute: true });
      return filePaths.map(filePath => ({
        from: filePath,
        to: path.resolve(outDir, path.basename(filePath))
      }));
    }
    if (typeof item === "object") {
      return [
        {
          from: path.resolve(item.from),
          to: path.resolve(outDir, item.to ? item.to : path.basename(item.from))
        }
      ];
    }
    return [];
  });
  const additionalFiles = (await Promise.all(copies)).flat();

  // 加载器配置
  const loaders = {
    image: {
      baseDir: config.loaders?.image?.baseDir || "assets"
    }
  };

  // 启用代码分割
  const codeSplitting = config.codeSplitting ?? true;

  // 代码分割分组
  const advancedChunks: NonNullable<OutputOptions["advancedChunks"]> = {
    groups: [
      // 外部依赖包
      {
        priority: Number.MAX_SAFE_INTEGER,
        test: /node_modules|bettergi-script-toolchain[\\/]packages/,
        name(moduleId) {
          const pkgInfo = lookupPackageInfo(moduleId);
          return typeof pkgInfo?.name === "string" ? pkgInfo.name.replace("/", "+") : undefined;
        }
      },
      // 虚拟模块
      {
        priority: Number.MAX_SAFE_INTEGER,
        test: /^virtual:.+:/,
        name(moduleId) {
          const [virtual, name] = moduleId.split(":");
          return `${virtual}@${name}`;
        }
      },
      // rolldown
      {
        priority: Number.MAX_SAFE_INTEGER,
        test: /rolldown:runtime/,
        name: "rolldown-runtime"
      },
      // 自定义分组
      ...(config.chunkGroups || [])
    ]
  };

  // Tree Shaking
  const treeshake = config.treeshake ?? {
    moduleSideEffects: false,
    propertyReadSideEffects: false
  };

  // 启用脚本压缩
  const minify = config.minify ?? false;

  // 文件头部注释
  const defaultBanner = `/**
 * Better Genshin Impact JavaScript
 * Bundled with BetterGI CLI (https://www.npmjs.com/package/@bettergi/cli)
 * 
 * This file is automatically generated and should not be edited.
 */`;
  const banner =
    config.banner === false
      ? ""
      : typeof config.banner === "string"
        ? config.banner
        : defaultBanner;

  // 监听文件变化（支持通配符）
  const include = [configFile, "package.json", assetsDir].concat(config.watch || []);
  const watches = include.map(item => glob(item, { cwd: path.resolve("."), absolute: true }));
  const watch = (await Promise.all(watches)).flat().filter(Boolean) as string[];

  return {
    main,
    assetsDir,
    outDir,
    additionalFiles,
    loaders,
    codeSplitting,
    advancedChunks,
    treeshake,
    minify,
    banner,
    watch
  };
};
