import type { ClrHostValue, EnumTypeTrait, HostType } from "../Microsoft/ClearScript/HostType";
import "../System/Enum";
import "../System/IComparable";
import "../System/IConvertible";
import "../System/IFormattable";
import "../System/ISpanFormattable";

declare const colorConversionCodesBrand: unique symbol;
export interface ColorConversionCodes extends ClrHostValue {
  readonly [colorConversionCodesBrand]: true;
}

declare global {
  namespace OpenCvSharp {
    type ColorConversionCodes = import("./ColorConversionCodes").ColorConversionCodes;
  }
}

export interface ColorConversionCodesHostType extends HostType<
  ColorConversionCodes,
  EnumTypeTrait
> {
  readonly bgR2BGRA: ColorConversionCodes;
  readonly rgB2RGBA: ColorConversionCodes;
  readonly bgrA2BGR: ColorConversionCodes;
  readonly rgbA2RGB: ColorConversionCodes;
  readonly bgR2RGBA: ColorConversionCodes;
  readonly rgB2BGRA: ColorConversionCodes;
  readonly rgbA2BGR: ColorConversionCodes;
  readonly bgrA2RGB: ColorConversionCodes;
  readonly bgR2RGB: ColorConversionCodes;
  readonly rgB2BGR: ColorConversionCodes;
  readonly bgrA2RGBA: ColorConversionCodes;
  readonly rgbA2BGRA: ColorConversionCodes;
  readonly bgR2GRAY: ColorConversionCodes;
  readonly rgB2GRAY: ColorConversionCodes;
  readonly graY2BGR: ColorConversionCodes;
  readonly graY2RGB: ColorConversionCodes;
  readonly graY2BGRA: ColorConversionCodes;
  readonly graY2RGBA: ColorConversionCodes;
  readonly bgrA2GRAY: ColorConversionCodes;
  readonly rgbA2GRAY: ColorConversionCodes;
  readonly bgR2BGR565: ColorConversionCodes;
  readonly rgB2BGR565: ColorConversionCodes;
  readonly bgR5652BGR: ColorConversionCodes;
  readonly bgR5652RGB: ColorConversionCodes;
  readonly bgrA2BGR565: ColorConversionCodes;
  readonly rgbA2BGR565: ColorConversionCodes;
  readonly bgR5652BGRA: ColorConversionCodes;
  readonly bgR5652RGBA: ColorConversionCodes;
  readonly graY2BGR565: ColorConversionCodes;
  readonly bgR5652GRAY: ColorConversionCodes;
  readonly bgR2BGR555: ColorConversionCodes;
  readonly rgB2BGR555: ColorConversionCodes;
  readonly bgR5552BGR: ColorConversionCodes;
  readonly bgR5552RGB: ColorConversionCodes;
  readonly bgrA2BGR555: ColorConversionCodes;
  readonly rgbA2BGR555: ColorConversionCodes;
  readonly bgR5552BGRA: ColorConversionCodes;
  readonly bgR5552RGBA: ColorConversionCodes;
  readonly graY2BGR555: ColorConversionCodes;
  readonly bgR5552GRAY: ColorConversionCodes;
  readonly bgR2XYZ: ColorConversionCodes;
  readonly rgB2XYZ: ColorConversionCodes;
  readonly xyZ2BGR: ColorConversionCodes;
  readonly xyZ2RGB: ColorConversionCodes;
  readonly bgR2YCrCb: ColorConversionCodes;
  readonly rgB2YCrCb: ColorConversionCodes;
  readonly yCrCb2BGR: ColorConversionCodes;
  readonly yCrCb2RGB: ColorConversionCodes;
  readonly bgR2HSV: ColorConversionCodes;
  readonly rgB2HSV: ColorConversionCodes;
  readonly bgR2Lab: ColorConversionCodes;
  readonly rgB2Lab: ColorConversionCodes;
  readonly bgR2Luv: ColorConversionCodes;
  readonly rgB2Luv: ColorConversionCodes;
  readonly bgR2HLS: ColorConversionCodes;
  readonly rgB2HLS: ColorConversionCodes;
  readonly hsV2BGR: ColorConversionCodes;
  readonly hsV2RGB: ColorConversionCodes;
  readonly lab2BGR: ColorConversionCodes;
  readonly lab2RGB: ColorConversionCodes;
  readonly luv2BGR: ColorConversionCodes;
  readonly luv2RGB: ColorConversionCodes;
  readonly hlS2BGR: ColorConversionCodes;
  readonly hlS2RGB: ColorConversionCodes;
  readonly bgR2HSV_FULL: ColorConversionCodes;
  readonly rgB2HSV_FULL: ColorConversionCodes;
  readonly bgR2HLS_FULL: ColorConversionCodes;
  readonly rgB2HLS_FULL: ColorConversionCodes;
  readonly hsV2BGR_FULL: ColorConversionCodes;
  readonly hsV2RGB_FULL: ColorConversionCodes;
  readonly hlS2BGR_FULL: ColorConversionCodes;
  readonly hlS2RGB_FULL: ColorConversionCodes;
  readonly lbgR2Lab: ColorConversionCodes;
  readonly lrgB2Lab: ColorConversionCodes;
  readonly lbgR2Luv: ColorConversionCodes;
  readonly lrgB2Luv: ColorConversionCodes;
  readonly lab2LBGR: ColorConversionCodes;
  readonly lab2LRGB: ColorConversionCodes;
  readonly luv2LBGR: ColorConversionCodes;
  readonly luv2LRGB: ColorConversionCodes;
  readonly bgR2YUV: ColorConversionCodes;
  readonly rgB2YUV: ColorConversionCodes;
  readonly yuV2BGR: ColorConversionCodes;
  readonly yuV2RGB: ColorConversionCodes;
  readonly yuV2RGB_NV12: ColorConversionCodes;
  readonly yuV2BGR_NV12: ColorConversionCodes;
  readonly yuV2RGB_NV21: ColorConversionCodes;
  readonly yuV2BGR_NV21: ColorConversionCodes;
  readonly yuV420sp2RGB: ColorConversionCodes;
  readonly yuV420sp2BGR: ColorConversionCodes;
  readonly yuV2RGBA_NV12: ColorConversionCodes;
  readonly yuV2BGRA_NV12: ColorConversionCodes;
  readonly yuV2RGBA_NV21: ColorConversionCodes;
  readonly yuV2BGRA_NV21: ColorConversionCodes;
  readonly yuV420sp2RGBA: ColorConversionCodes;
  readonly yuV420sp2BGRA: ColorConversionCodes;
  readonly yuV2RGB_YV12: ColorConversionCodes;
  readonly yuV2BGR_YV12: ColorConversionCodes;
  readonly yuV2RGB_IYUV: ColorConversionCodes;
  readonly yuV2BGR_IYUV: ColorConversionCodes;
  readonly yuV2RGB_I420: ColorConversionCodes;
  readonly yuV2BGR_I420: ColorConversionCodes;
  readonly yuV420p2RGB: ColorConversionCodes;
  readonly yuV420p2BGR: ColorConversionCodes;
  readonly yuV2RGBA_YV12: ColorConversionCodes;
  readonly yuV2BGRA_YV12: ColorConversionCodes;
  readonly yuV2RGBA_IYUV: ColorConversionCodes;
  readonly yuV2BGRA_IYUV: ColorConversionCodes;
  readonly yuV2RGBA_I420: ColorConversionCodes;
  readonly yuV2BGRA_I420: ColorConversionCodes;
  readonly yuV420p2RGBA: ColorConversionCodes;
  readonly yuV420p2BGRA: ColorConversionCodes;
  readonly yuV2GRAY_420: ColorConversionCodes;
  readonly yuV2GRAY_NV21: ColorConversionCodes;
  readonly yuV2GRAY_NV12: ColorConversionCodes;
  readonly yuV2GRAY_YV12: ColorConversionCodes;
  readonly yuV2GRAY_IYUV: ColorConversionCodes;
  readonly yuV2GRAY_I420: ColorConversionCodes;
  readonly yuV420sp2GRAY: ColorConversionCodes;
  readonly yuV420p2GRAY: ColorConversionCodes;
  readonly yuV2RGB_UYVY: ColorConversionCodes;
  readonly yuV2BGR_UYVY: ColorConversionCodes;
  readonly yuV2RGB_Y422: ColorConversionCodes;
  readonly yuV2BGR_Y422: ColorConversionCodes;
  readonly yuV2RGB_UYNV: ColorConversionCodes;
  readonly yuV2BGR_UYNV: ColorConversionCodes;
  readonly yuV2RGBA_UYVY: ColorConversionCodes;
  readonly yuV2BGRA_UYVY: ColorConversionCodes;
  readonly yuV2RGBA_Y422: ColorConversionCodes;
  readonly yuV2BGRA_Y422: ColorConversionCodes;
  readonly yuV2RGBA_UYNV: ColorConversionCodes;
  readonly yuV2BGRA_UYNV: ColorConversionCodes;
  readonly yuV2RGB_YUY2: ColorConversionCodes;
  readonly yuV2BGR_YUY2: ColorConversionCodes;
  readonly yuV2RGB_YVYU: ColorConversionCodes;
  readonly yuV2BGR_YVYU: ColorConversionCodes;
  readonly yuV2RGB_YUYV: ColorConversionCodes;
  readonly yuV2BGR_YUYV: ColorConversionCodes;
  readonly yuV2RGB_YUNV: ColorConversionCodes;
  readonly yuV2BGR_YUNV: ColorConversionCodes;
  readonly yuV2RGBA_YUY2: ColorConversionCodes;
  readonly yuV2BGRA_YUY2: ColorConversionCodes;
  readonly yuV2RGBA_YVYU: ColorConversionCodes;
  readonly yuV2BGRA_YVYU: ColorConversionCodes;
  readonly yuV2RGBA_YUYV: ColorConversionCodes;
  readonly yuV2BGRA_YUYV: ColorConversionCodes;
  readonly yuV2RGBA_YUNV: ColorConversionCodes;
  readonly yuV2BGRA_YUNV: ColorConversionCodes;
  readonly yuV2GRAY_UYVY: ColorConversionCodes;
  readonly yuV2GRAY_YUY2: ColorConversionCodes;
  readonly yuV2GRAY_Y422: ColorConversionCodes;
  readonly yuV2GRAY_UYNV: ColorConversionCodes;
  readonly yuV2GRAY_YVYU: ColorConversionCodes;
  readonly yuV2GRAY_YUYV: ColorConversionCodes;
  readonly yuV2GRAY_YUNV: ColorConversionCodes;
  readonly rgbA2mRGBA: ColorConversionCodes;
  readonly mRGBA2RGBA: ColorConversionCodes;
  readonly rgB2YUV_I420: ColorConversionCodes;
  readonly bgR2YUV_I420: ColorConversionCodes;
  readonly rgB2YUV_IYUV: ColorConversionCodes;
  readonly bgR2YUV_IYUV: ColorConversionCodes;
  readonly rgbA2YUV_I420: ColorConversionCodes;
  readonly bgrA2YUV_I420: ColorConversionCodes;
  readonly rgbA2YUV_IYUV: ColorConversionCodes;
  readonly bgrA2YUV_IYUV: ColorConversionCodes;
  readonly rgB2YUV_YV12: ColorConversionCodes;
  readonly bgR2YUV_YV12: ColorConversionCodes;
  readonly rgbA2YUV_YV12: ColorConversionCodes;
  readonly bgrA2YUV_YV12: ColorConversionCodes;
  readonly bayerBG2BGR: ColorConversionCodes;
  readonly bayerGB2BGR: ColorConversionCodes;
  readonly bayerRG2BGR: ColorConversionCodes;
  readonly bayerGR2BGR: ColorConversionCodes;
  readonly bayerBG2RGB: ColorConversionCodes;
  readonly bayerGB2RGB: ColorConversionCodes;
  readonly bayerRG2RGB: ColorConversionCodes;
  readonly bayerGR2RGB: ColorConversionCodes;
  readonly bayerBG2GRAY: ColorConversionCodes;
  readonly bayerGB2GRAY: ColorConversionCodes;
  readonly bayerRG2GRAY: ColorConversionCodes;
  readonly bayerGR2GRAY: ColorConversionCodes;
  readonly bayerBG2BGR_VNG: ColorConversionCodes;
  readonly bayerGB2BGR_VNG: ColorConversionCodes;
  readonly bayerRG2BGR_VNG: ColorConversionCodes;
  readonly bayerGR2BGR_VNG: ColorConversionCodes;
  readonly bayerBG2RGB_VNG: ColorConversionCodes;
  readonly bayerGB2RGB_VNG: ColorConversionCodes;
  readonly bayerRG2RGB_VNG: ColorConversionCodes;
  readonly bayerGR2RGB_VNG: ColorConversionCodes;
  readonly bayerBG2BGR_EA: ColorConversionCodes;
  readonly bayerGB2BGR_EA: ColorConversionCodes;
  readonly bayerRG2BGR_EA: ColorConversionCodes;
  readonly bayerGR2BGR_EA: ColorConversionCodes;
  readonly bayerBG2RGB_EA: ColorConversionCodes;
  readonly bayerGB2RGB_EA: ColorConversionCodes;
  readonly bayerRG2RGB_EA: ColorConversionCodes;
  readonly bayerGR2RGB_EA: ColorConversionCodes;
  readonly colorcvT_MAX: ColorConversionCodes;
}

export {};
