import add_new from "../../../images/UI_TouchIcon/UI_TouchIcon_AddNew.png?path";
import again from "../../../images/UI_TouchIcon/UI_TouchIcon_Again.png?path";
import cancel from "../../../images/UI_TouchIcon/UI_TouchIcon_Cancel.png?path";
import check_prequest from "../../../images/UI_TouchIcon/UI_TouchIcon_Check_PreQuest.png?path";
import common_refresh from "../../../images/UI_TouchIcon/UI_TouchIcon_CommonRefresh.png?path";
import community from "../../../images/UI_TouchIcon/UI_TouchIcon_Community.png?path";
import complete from "../../../images/UI_TouchIcon/UI_TouchIcon_Complete.png?path";
import contribute from "../../../images/UI_TouchIcon/UI_TouchIcon_Contribute.png?path";
import contribute_all from "../../../images/UI_TouchIcon/UI_TouchIcon_ContributeAll.png?path";
import copy from "../../../images/UI_TouchIcon/UI_TouchIcon_Copy.png?path";
import discard from "../../../images/UI_TouchIcon/UI_TouchIcon_Discard.png?path";
import discharge from "../../../images/UI_TouchIcon/UI_TouchIcon_Discharge.png?path";
import download from "../../../images/UI_TouchIcon/UI_TouchIcon_Download.png?path";
import equip from "../../../images/UI_TouchIcon/UI_TouchIcon_Equip.png?path";
import exit from "../../../images/UI_TouchIcon/UI_TouchIcon_Exit.png?path";
import fast_open from "../../../images/UI_TouchIcon/UI_TouchIcon_FastOpen.png?path";
import fetch from "../../../images/UI_TouchIcon/UI_TouchIcon_Fetch.png?path";
import fetch_all from "../../../images/UI_TouchIcon/UI_TouchIcon_FetchAll.png?path";
import import_icon from "../../../images/UI_TouchIcon/UI_TouchIcon_Import.png?path";
import info from "../../../images/UI_TouchIcon/UI_TouchIcon_Info.png?path";
import invite from "../../../images/UI_TouchIcon/UI_TouchIcon_Invite.png?path";
import lock from "../../../images/UI_TouchIcon/UI_TouchIcon_Lock.png?path";
import mission from "../../../images/UI_TouchIcon/UI_TouchIcon_Mission.png?path";
import music from "../../../images/UI_TouchIcon/UI_TouchIcon_Music.png?path";
import music_edit from "../../../images/UI_TouchIcon/UI_TouchIcon_MusicEdit.png?path";
import option from "../../../images/UI_TouchIcon/UI_TouchIcon_Option.png?path";
import pause from "../../../images/UI_TouchIcon/UI_TouchIcon_Pause.png?path";
import playing from "../../../images/UI_TouchIcon/UI_TouchIcon_Playing.png?path";
import prompt from "../../../images/UI_TouchIcon/UI_TouchIcon_Prompt.png?path";
import quick_filling_in from "../../../images/UI_TouchIcon/UI_TouchIcon_QuickFillingIn.png?path";
import quit from "../../../images/UI_TouchIcon/UI_TouchIcon_Quit.png?path";
import refresh from "../../../images/UI_TouchIcon/UI_TouchIcon_Refresh.png?path";
import refuse from "../../../images/UI_TouchIcon/UI_TouchIcon_Refuse.png?path";
import remove from "../../../images/UI_TouchIcon/UI_TouchIcon_Remove.png?path";
import review from "../../../images/UI_TouchIcon/UI_TouchIcon_Review.png?path";
import reward from "../../../images/UI_TouchIcon/UI_TouchIcon_Reward.png?path";
import setting from "../../../images/UI_TouchIcon/UI_TouchIcon_Setting.png?path";
import share from "../../../images/UI_TouchIcon/UI_TouchIcon_Share.png?path";
import shop from "../../../images/UI_TouchIcon/UI_TouchIcon_Shop.png?path";
import speed_up from "../../../images/UI_TouchIcon/UI_TouchIcon_SpeedUp.png?path";
import stop from "../../../images/UI_TouchIcon/UI_TouchIcon_Stop.png?path";
import team from "../../../images/UI_TouchIcon/UI_TouchIcon_Team.png?path";
import team_fast from "../../../images/UI_TouchIcon/UI_TouchIcon_TeamFast.png?path";
import track from "../../../images/UI_TouchIcon/UI_TouchIcon_Track.png?path";
import use from "../../../images/UI_TouchIcon/UI_TouchIcon_Use.png?path";
import use_default from "../../../images/UI_TouchIcon/UI_TouchIcon_UseDefault.png?path";
import virtual from "../../../images/UI_TouchIcon/UI_TouchIcon_Virtual.png?path";
import { createDefaultResizable } from "../../utils/resizable";

/** -------------------------------- 实体按钮 -------------------------------- */
export const ui_touch_icon_add_new = createDefaultResizable(add_new, 44, 44);
export const ui_touch_icon_again = createDefaultResizable(again, 44, 44);
export const ui_touch_icon_cancel = createDefaultResizable(cancel, 44, 44);
export const ui_touch_icon_check_prequest = createDefaultResizable(check_prequest, 44, 44);
export const ui_touch_icon_common_refresh = createDefaultResizable(common_refresh, 44, 44);
export const ui_touch_icon_community = createDefaultResizable(community, 44, 44);
export const ui_touch_icon_complete = createDefaultResizable(complete, 44, 44);
export const ui_touch_icon_contribute = createDefaultResizable(contribute, 44, 44);
export const ui_touch_icon_contribute_all = createDefaultResizable(contribute_all, 44, 44);
export const ui_touch_icon_copy = createDefaultResizable(copy, 44, 44);
export const ui_touch_icon_discard = createDefaultResizable(discard, 44, 44);
export const ui_touch_icon_discharge = createDefaultResizable(discharge, 44, 44);
export const ui_touch_icon_download = createDefaultResizable(download, 44, 44);
export const ui_touch_icon_equip = createDefaultResizable(equip, 44, 44);
export const ui_touch_icon_exit = createDefaultResizable(exit, 44, 44);
export const ui_touch_icon_fast_open = createDefaultResizable(fast_open, 44, 44);
export const ui_touch_icon_fetch = createDefaultResizable(fetch, 44, 44);
export const ui_touch_icon_fetch_all = createDefaultResizable(fetch_all, 44, 44);
export const ui_touch_icon_import_icon = createDefaultResizable(import_icon, 44, 44);
export const ui_touch_icon_info = createDefaultResizable(info, 44, 44);
export const ui_touch_icon_invite = createDefaultResizable(invite, 44, 44);
export const ui_touch_icon_lock = createDefaultResizable(lock, 44, 44);
export const ui_touch_icon_mission = createDefaultResizable(mission, 44, 44);
export const ui_touch_icon_music = createDefaultResizable(music, 44, 44);
export const ui_touch_icon_music_edit = createDefaultResizable(music_edit, 44, 44);
export const ui_touch_icon_option = createDefaultResizable(option, 44, 44);
export const ui_touch_icon_pause = createDefaultResizable(pause, 44, 44);
export const ui_touch_icon_playing = createDefaultResizable(playing, 44, 44);
export const ui_touch_icon_prompt = createDefaultResizable(prompt, 44, 44);
export const ui_touch_icon_quick_filling_in = createDefaultResizable(quick_filling_in, 44, 44);
export const ui_touch_icon_quit = createDefaultResizable(quit, 44, 44);
export const ui_touch_icon_refresh = createDefaultResizable(refresh, 44, 44);
export const ui_touch_icon_refuse = createDefaultResizable(refuse, 44, 44);
export const ui_touch_icon_remove = createDefaultResizable(remove, 44, 44);
export const ui_touch_icon_review = createDefaultResizable(review, 44, 44);
export const ui_touch_icon_reward = createDefaultResizable(reward, 44, 44);
export const ui_touch_icon_setting = createDefaultResizable(setting, 44, 44);
export const ui_touch_icon_share = createDefaultResizable(share, 44, 44);
export const ui_touch_icon_shop = createDefaultResizable(shop, 44, 44);
export const ui_touch_icon_speed_up = createDefaultResizable(speed_up, 44, 44);
export const ui_touch_icon_stop = createDefaultResizable(stop, 44, 44);
export const ui_touch_icon_team = createDefaultResizable(team, 44, 44);
export const ui_touch_icon_team_fast = createDefaultResizable(team_fast, 44, 44);
export const ui_touch_icon_track = createDefaultResizable(track, 44, 44);
export const ui_touch_icon_use = createDefaultResizable(use, 44, 44);
export const ui_touch_icon_use_default = createDefaultResizable(use_default, 44, 44);
export const ui_touch_icon_virtual = createDefaultResizable(virtual, 44, 44);
