import album from "../../../images/UI_TouchIcon/UI_TouchIcon_Album.png?path";
import answer from "../../../images/UI_TouchIcon/UI_TouchIcon_Answer.png?path";
import audio from "../../../images/UI_TouchIcon/UI_TouchIcon_Audio.png?path";
import collocation from "../../../images/UI_TouchIcon/UI_TouchIcon_Collocation.png?path";
import edit from "../../../images/UI_TouchIcon/UI_TouchIcon_Edit.png?path";
import help from "../../../images/UI_TouchIcon/UI_TouchIcon_Help.png?path";
import hide_ui from "../../../images/UI_TouchIcon/UI_TouchIcon_HideUI.png?path";
import info1 from "../../../images/UI_TouchIcon/UI_TouchIcon_Info1.png?path";
import info2 from "../../../images/UI_TouchIcon/UI_TouchIcon_Info2.png?path";
import info_ugc from "../../../images/UI_TouchIcon/UI_TouchIcon_Info_UGC.png?path";
import location from "../../../images/UI_TouchIcon/UI_TouchIcon_Location.png?path";
import look_over from "../../../images/UI_TouchIcon/UI_TouchIcon_LookOver.png?path";
import map from "../../../images/UI_TouchIcon/UI_TouchIcon_Map.png?path";
import max from "../../../images/UI_TouchIcon/UI_TouchIcon_Max.png?path";
import minus from "../../../images/UI_TouchIcon/UI_TouchIcon_Minus.png?path";
import minus_b from "../../../images/UI_TouchIcon/UI_TouchIcon_MinusB.png?path";
import minus_b_ugc from "../../../images/UI_TouchIcon/UI_TouchIcon_MinusB_UGC.png?path";
import minus_ugc from "../../../images/UI_TouchIcon/UI_TouchIcon_Minus_UGC.png?path";
import more from "../../../images/UI_TouchIcon/UI_TouchIcon_More.png?path";
import play from "../../../images/UI_TouchIcon/UI_TouchIcon_Play.png?path";
import play_b from "../../../images/UI_TouchIcon/UI_TouchIcon_PlayB.png?path";
import plus from "../../../images/UI_TouchIcon/UI_TouchIcon_Plus.png?path";
import plus_b from "../../../images/UI_TouchIcon/UI_TouchIcon_PlusB.png?path";
import plus_b_ugc from "../../../images/UI_TouchIcon/UI_TouchIcon_PlusB_UGC.png?path";
import plus_ugc from "../../../images/UI_TouchIcon/UI_TouchIcon_Plus_UGC.png?path";
import prev from "../../../images/UI_TouchIcon/UI_TouchIcon_Prev.png?path";
import quest_preview from "../../../images/UI_TouchIcon/UI_TouchIcon_QuestPreview.png?path";
import redo from "../../../images/UI_TouchIcon/UI_TouchIcon_Redo.png?path";
import reset from "../../../images/UI_TouchIcon/UI_TouchIcon_Reset.png?path";
import reward2 from "../../../images/UI_TouchIcon/UI_TouchIcon_Reward2.png?path";
import skip from "../../../images/UI_TouchIcon/UI_TouchIcon_Skip.png?path";
import story from "../../../images/UI_TouchIcon/UI_TouchIcon_Story.png?path";
import suspend from "../../../images/UI_TouchIcon/UI_TouchIcon_Suspend.png?path";
import suspend_b from "../../../images/UI_TouchIcon/UI_TouchIcon_SuspendB.png?path";
import talk_review from "../../../images/UI_TouchIcon/UI_TouchIcon_TalkReview.png?path";
import un_lock from "../../../images/UI_TouchIcon/UI_TouchIcon_UnLock.png?path";
import { createDefaultResizable } from "../../utils/resizable";

export const ui_touch_icon_album = createDefaultResizable(album, 44, 44);
export const ui_touch_icon_answer = createDefaultResizable(answer, 44, 44);
export const ui_touch_icon_audio = createDefaultResizable(audio, 44, 44);
export const ui_touch_icon_collocation = createDefaultResizable(collocation, 44, 44);
export const ui_touch_icon_edit = createDefaultResizable(edit, 44, 44);
export const ui_touch_icon_help = createDefaultResizable(help, 44, 44);
export const ui_touch_icon_hide_ui = createDefaultResizable(hide_ui, 44, 44);
export const ui_touch_icon_info2 = createDefaultResizable(info2, 44, 44);
export const ui_touch_icon_location = createDefaultResizable(location, 44, 44);
export const ui_touch_icon_look_over = createDefaultResizable(look_over, 44, 44);
export const ui_touch_icon_map = createDefaultResizable(map, 44, 44);
export const ui_touch_icon_max = createDefaultResizable(max, 44, 44);
export const ui_touch_icon_minus = createDefaultResizable(minus, 44, 44);
export const ui_touch_icon_more = createDefaultResizable(more, 44, 44);
export const ui_touch_icon_play = createDefaultResizable(play, 44, 44);
export const ui_touch_icon_plus = createDefaultResizable(plus, 44, 44);
export const ui_touch_icon_prev = createDefaultResizable(prev, 44, 44);
export const ui_touch_icon_quest_preview = createDefaultResizable(quest_preview, 44, 44);
export const ui_touch_icon_redo = createDefaultResizable(redo, 44, 44);
export const ui_touch_icon_reset = createDefaultResizable(reset, 44, 44);
export const ui_touch_icon_reward2 = createDefaultResizable(reward2, 44, 44);
export const ui_touch_icon_skip = createDefaultResizable(skip, 44, 44);
export const ui_touch_icon_story = createDefaultResizable(story, 44, 44);
export const ui_touch_icon_suspend = createDefaultResizable(suspend, 44, 44);
export const ui_touch_icon_talk_review = createDefaultResizable(talk_review, 44, 44);
export const ui_touch_icon_un_lock = createDefaultResizable(un_lock, 44, 44);

/** -------------------------------- 调节控件按钮 -------------------------------- */
export const ui_touch_icon_info1 = createDefaultResizable(info1, 44, 44);
export const ui_touch_icon_minus_b = createDefaultResizable(minus_b, 48, 48);
export const ui_touch_icon_play_b = createDefaultResizable(play_b, 44, 44);
export const ui_touch_icon_plus_b = createDefaultResizable(plus_b, 48, 48);
export const ui_touch_icon_suspend_b = createDefaultResizable(suspend_b, 44, 44);

/** -------------------------------- UGC按钮 -------------------------------- */
export const ui_touch_icon_info_ugc = createDefaultResizable(info_ugc, 44, 44);
export const ui_touch_icon_minus_b_ugc = createDefaultResizable(minus_b_ugc, 44, 44);
export const ui_touch_icon_minus_ugc = createDefaultResizable(minus_ugc, 44, 44);
export const ui_touch_icon_plus_b_ugc = createDefaultResizable(plus_b_ugc, 44, 44);
export const ui_touch_icon_plus_ugc = createDefaultResizable(plus_ugc, 44, 44);
