import type { HostTypeCollection } from "../types/Microsoft/ClearScript/HostTypeCollection";
import type { PropertyBag } from "../types/Microsoft/ClearScript/PropertyBag";
import type { AKAZEHostType } from "../types/OpenCvSharp/AKAZE";
import type { AKAZEDescriptorTypeHostType } from "../types/OpenCvSharp/AKAZEDescriptorType";
import type { AccessFlagHostType } from "../types/OpenCvSharp/AccessFlag";
import type { AdaptiveThresholdTypesHostType } from "../types/OpenCvSharp/AdaptiveThresholdTypes";
import type { AgastFeatureDetectorHostType } from "../types/OpenCvSharp/AgastFeatureDetector";
import type { AlgorithmHostType } from "../types/OpenCvSharp/Algorithm";
import type { AlgorithmParamTypeHostType } from "../types/OpenCvSharp/AlgorithmParamType";
import type { CornerRefineMethodHostType } from "../types/OpenCvSharp/Aruco/CornerRefineMethod";
import type { CvArucoHostType } from "../types/OpenCvSharp/Aruco/CvAruco";
import type { DetectorParametersHostType } from "../types/OpenCvSharp/Aruco/DetectorParameters";
import type { DictionaryHostType } from "../types/OpenCvSharp/Aruco/Dictionary";
import type { PredefinedDictionaryNameHostType } from "../types/OpenCvSharp/Aruco/PredefinedDictionaryName";
import type { BFMatcherHostType } from "../types/OpenCvSharp/BFMatcher";
import type { BOWImgDescriptorExtractorHostType } from "../types/OpenCvSharp/BOWImgDescriptorExtractor";
import type { BOWKMeansTrainerHostType } from "../types/OpenCvSharp/BOWKMeansTrainer";
import type { BOWTrainerHostType } from "../types/OpenCvSharp/BOWTrainer";
import type { BRISKHostType } from "../types/OpenCvSharp/BRISK";
import type { BackgroundSubtractorHostType } from "../types/OpenCvSharp/BackgroundSubtractor";
import type { BackgroundSubtractorGMGHostType } from "../types/OpenCvSharp/BackgroundSubtractorGMG";
import type { BackgroundSubtractorKNNHostType } from "../types/OpenCvSharp/BackgroundSubtractorKNN";
import type { BackgroundSubtractorMOGHostType } from "../types/OpenCvSharp/BackgroundSubtractorMOG";
import type { BackgroundSubtractorMOG2HostType } from "../types/OpenCvSharp/BackgroundSubtractorMog2";
import type { BorderTypesHostType } from "../types/OpenCvSharp/BorderTypes";
import type { BroxOpticalFlowHostType } from "../types/OpenCvSharp/BroxOpticalFlow";
import type { ButtonTypeHostType } from "../types/OpenCvSharp/ButtonType";
import type { CLAHEHostType } from "../types/OpenCvSharp/CLAHE";
import type { CalibrateCRFHostType } from "../types/OpenCvSharp/CalibrateCRF";
import type { CalibrateDebevecHostType } from "../types/OpenCvSharp/CalibrateDebevec";
import type { CalibrateRobertsonHostType } from "../types/OpenCvSharp/CalibrateRobertson";
import type { CalibrationFlagsHostType } from "../types/OpenCvSharp/CalibrationFlags";
import type { CameraChannelsHostType } from "../types/OpenCvSharp/CameraChannels";
import type { CapturePosAviRatioHostType } from "../types/OpenCvSharp/CapturePosRatio";
import type { CaptureTypeHostType } from "../types/OpenCvSharp/CaptureType";
import type { CascadeClassifierHostType } from "../types/OpenCvSharp/CascadeClassifier";
import type { ChessboardFlagsHostType } from "../types/OpenCvSharp/ChessboardFlags";
import type { CircleSegmentHostType } from "../types/OpenCvSharp/CircleSegment";
import type { CmpTypeHostType } from "../types/OpenCvSharp/CmpType";
import type { ColorConversionCodesHostType } from "../types/OpenCvSharp/ColorConversionCodes";
import type { ColormapTypesHostType } from "../types/OpenCvSharp/ColormapTypes";
import type { ConnectedComponentsHostType } from "../types/OpenCvSharp/ConnectedComponent";
import type { ConnectedComponentsAlgorithmsTypesHostType } from "../types/OpenCvSharp/ConnectedComponentsAlgorithmsTypes";
import type { ConnectedComponentsTypesHostType } from "../types/OpenCvSharp/ConnectedComponentsTypes";
import type { ContourApproximationModesHostType } from "../types/OpenCvSharp/ContourApproximationModes";
import type { ConvertImageModesHostType } from "../types/OpenCvSharp/ConvertImageModes";
import type { CovarFlagsHostType } from "../types/OpenCvSharp/CovarFlags";
import type { CpuFeaturesHostType } from "../types/OpenCvSharp/CpuFeatures";
import type { CriteriaTypesHostType } from "../types/OpenCvSharp/CriteriaTypes";
import type { Cv2HostType } from "../types/OpenCvSharp/Cv2";
import type { CvErrorCallbackHostType } from "../types/OpenCvSharp/CvErrorCallback";
import type { CvObjectHostType } from "../types/OpenCvSharp/CvObject";
import type { CvTrackbarHostType } from "../types/OpenCvSharp/CvTrackbar";
import type { DMatchHostType } from "../types/OpenCvSharp/DMatch";
import type { DctFlagsHostType } from "../types/OpenCvSharp/DctFlags";
import type { DecompTypesHostType } from "../types/OpenCvSharp/DecompTypes";
import type { DenseOpticalFlowExtHostType } from "../types/OpenCvSharp/DenseOpticalFlowExt";
import type { DescriptorMatcherHostType } from "../types/OpenCvSharp/DescriptorMatcher";
import type { AffineBestOf2NearestMatcherHostType } from "../types/OpenCvSharp/Detail/AffineBestOf2NearestMatcher";
import type { BestOf2NearestMatcherHostType } from "../types/OpenCvSharp/Detail/BestOf2NearestMatcher";
import type { CvDetailHostType } from "../types/OpenCvSharp/Detail/CvDetail";
import type { FeaturesMatcherHostType } from "../types/OpenCvSharp/Detail/FeaturesMatcher";
import type { ImageFeaturesHostType } from "../types/OpenCvSharp/Detail/ImageFeatures";
import type { WImageFeaturesHostType } from "../types/OpenCvSharp/Detail/ImageFeatures";
import type { MatchesInfoHostType } from "../types/OpenCvSharp/Detail/MatchesInfo";
import type { BlenderHostType } from "../types/OpenCvSharp/Detail/Stitcher";
import type { BundleAdjusterBaseHostType } from "../types/OpenCvSharp/Detail/Stitcher";
import type { CameraParamsHostType } from "../types/OpenCvSharp/Detail/Stitcher";
import type { ExposureCompensatorHostType } from "../types/OpenCvSharp/Detail/Stitcher";
import type { FeaturesFinderHostType } from "../types/OpenCvSharp/Detail/Stitcher";
import type { SeamFinderHostType } from "../types/OpenCvSharp/Detail/Stitcher";
import type { WarperCreatorHostType } from "../types/OpenCvSharp/Detail/Stitcher";
import type { WaveCorrectKindHostType } from "../types/OpenCvSharp/Detail/Stitcher";
import type { DftFlagsHostType } from "../types/OpenCvSharp/DftFlags";
import type { DisposableCvObjectHostType } from "../types/OpenCvSharp/DisposableCvObject";
import type { DisposableObjectHostType } from "../types/OpenCvSharp/DisposableObject";
import type { DistanceTransformLabelTypesHostType } from "../types/OpenCvSharp/DistanceTransformLabelTypes";
import type { DistanceTransformMasksHostType } from "../types/OpenCvSharp/DistanceTransformMasks";
import type { DistanceTypesHostType } from "../types/OpenCvSharp/DistanceTypes";
import type { DistributionTypeHostType } from "../types/OpenCvSharp/DistributionType";
import type { BackendHostType } from "../types/OpenCvSharp/Dnn/Backend";
import type { CvDnnHostType } from "../types/OpenCvSharp/Dnn/CvDnn";
import type { NetHostType } from "../types/OpenCvSharp/Dnn/Net";
import type { TargetHostType } from "../types/OpenCvSharp/Dnn/Target";
import type { DnnSuperResImplHostType } from "../types/OpenCvSharp/DnnSuperres/DnnSuperResImpl";
import type { DrawMatchesFlagsHostType } from "../types/OpenCvSharp/DrawMatchesFlags";
import type { DualTVL1OpticalFlowHostType } from "../types/OpenCvSharp/DualTVL1OpticalFlow";
import type { EMHostType } from "../types/OpenCvSharp/EM";
import type { EMStartStepHostType } from "../types/OpenCvSharp/EM";
import type { EMTypesHostType } from "../types/OpenCvSharp/EM";
import type { EdgePreservingMethodsHostType } from "../types/OpenCvSharp/EdgePreservingMethods";
import type { ErrorCodeHostType } from "../types/OpenCvSharp/ErrorCode";
import type { EssentialMatMethodHostType } from "../types/OpenCvSharp/EssentialMatMethod";
import type { FASTTypeHostType } from "../types/OpenCvSharp/FASTType";
import type { BasicFaceRecognizerHostType } from "../types/OpenCvSharp/Face/BasicFaceRecognizer";
import type { EigenFaceRecognizerHostType } from "../types/OpenCvSharp/Face/EigenFaceRecognizer";
import type { FaceRecognizerHostType } from "../types/OpenCvSharp/Face/FaceRecognizer";
import type { FacemarkHostType } from "../types/OpenCvSharp/Face/Facemark";
import type { FacemarkAAMHostType } from "../types/OpenCvSharp/Face/FacemarkAAM";
import type { FacemarkLBFHostType } from "../types/OpenCvSharp/Face/FacemarkLBF";
import type { FisherFaceRecognizerHostType } from "../types/OpenCvSharp/Face/FisherFaceRecognizer";
import type { LBPHFaceRecognizerHostType } from "../types/OpenCvSharp/Face/LBPHFaceRecognizer";
import type { FarnebackOpticalFlowHostType } from "../types/OpenCvSharp/FarnebackOpticalFlow";
import type { FastFeatureDetectorHostType } from "../types/OpenCvSharp/FastFeatureDetector";
import type { Feature2DHostType } from "../types/OpenCvSharp/Feature2D";
import type { SIFTHostType } from "../types/OpenCvSharp/Features2D/SIFT";
import type { FileNodeHostType } from "../types/OpenCvSharp/FileNode";
import type { FileNodeIteratorHostType } from "../types/OpenCvSharp/FileNodeIterator";
import type { FileStorageHostType } from "../types/OpenCvSharp/FileStorage";
import type { FindCirclesGridFlagsHostType } from "../types/OpenCvSharp/FindCirclesGridFlags";
import type { FishEyeCalibrationFlagsHostType } from "../types/OpenCvSharp/FishEyeCalibrationFlags";
import type { AutotunedIndexParamsHostType } from "../types/OpenCvSharp/Flann/AutotunedIndexParams";
import type { CompositeIndexParamsHostType } from "../types/OpenCvSharp/Flann/CompositeIndexParams";
import type { FlannCentersInitHostType } from "../types/OpenCvSharp/Flann/FlannCentersInit";
import type { FlannDistanceHostType } from "../types/OpenCvSharp/Flann/FlannDistance";
import type { IndexHostType } from "../types/OpenCvSharp/Flann/Index";
import type { IndexParamsHostType } from "../types/OpenCvSharp/Flann/IndexParams";
import type { KDTreeIndexParamsHostType } from "../types/OpenCvSharp/Flann/KDTreeIndexParams";
import type { KMeansIndexParamsHostType } from "../types/OpenCvSharp/Flann/KMeansIndexParams";
import type { LinearIndexParamsHostType } from "../types/OpenCvSharp/Flann/LinearIndexParams";
import type { LshIndexParamsHostType } from "../types/OpenCvSharp/Flann/LshIndexParams";
import type { SavedIndexParamsHostType } from "../types/OpenCvSharp/Flann/SavedIndexParams";
import type { SearchParamsHostType } from "../types/OpenCvSharp/Flann/SearchParams";
import type { FlannBasedMatcherHostType } from "../types/OpenCvSharp/FlannBasedMatcher";
import type { FlipModeHostType } from "../types/OpenCvSharp/FlipMode";
import type { FloodFillFlagsHostType } from "../types/OpenCvSharp/FloodFillFlags";
import type { FormatTypeHostType } from "../types/OpenCvSharp/FormatType";
import type { FourCCHostType } from "../types/OpenCvSharp/FourCC";
import type { FrameSourceHostType } from "../types/OpenCvSharp/FrameSource";
import type { FundamentalMatMethodsHostType } from "../types/OpenCvSharp/FundamentalMatMethods";
import type { GFTTDetectorHostType } from "../types/OpenCvSharp/GFTTDetector";
import type { GemmFlagsHostType } from "../types/OpenCvSharp/GemmFlags";
import type { GeneralizedHoughHostType } from "../types/OpenCvSharp/GeneralizedHough";
import type { GeneralizedHoughBallardHostType } from "../types/OpenCvSharp/GeneralizedHoughBallard";
import type { GeneralizedHoughGuilHostType } from "../types/OpenCvSharp/GeneralizedHoughGuil";
import type { GrabCutClassesHostType } from "../types/OpenCvSharp/GrabCutClasses";
import type { GrabCutModesHostType } from "../types/OpenCvSharp/GrabCutModes";
import type { DetectionROIHostType } from "../types/OpenCvSharp/HOGDescriptor";
import type { HOGDescriptorHostType } from "../types/OpenCvSharp/HOGDescriptor";
import type { HaarDetectionTypesHostType } from "../types/OpenCvSharp/HaarDetectionTypes";
import type { HandEyeCalibrationMethodHostType } from "../types/OpenCvSharp/HandEyeCalibrationMethod";
import type { HausdorffDistanceExtractorHostType } from "../types/OpenCvSharp/HausdorffDistanceExtractor";
import type { HersheyFontsHostType } from "../types/OpenCvSharp/HersheyFonts";
import type { HierarchyIndexHostType } from "../types/OpenCvSharp/HierarchyIndex";
import type { HistCompMethodsHostType } from "../types/OpenCvSharp/HistCompMethods";
import type { HistogramNormTypeHostType } from "../types/OpenCvSharp/HistogramNormType";
import type { HomographyMethodsHostType } from "../types/OpenCvSharp/HomographyMethods";
import type { HoughModesHostType } from "../types/OpenCvSharp/HoughModes";
import type { ICvPtrHolderHostType } from "../types/OpenCvSharp/ICvPtrHolder";
import type { IVecHostType } from "../types/OpenCvSharp/IVec";
import type { ImageEncodingParamHostType } from "../types/OpenCvSharp/ImageEncodingParam";
import type { AverageHashHostType } from "../types/OpenCvSharp/ImgHash/AverageHash";
import type { BlockMeanHashHostType } from "../types/OpenCvSharp/ImgHash/BlockMeanHash";
import type { BlockMeanHashModeHostType } from "../types/OpenCvSharp/ImgHash/BlockMeanHashMode";
import type { ColorMomentHashHostType } from "../types/OpenCvSharp/ImgHash/ColorMomentHash";
import type { ImgHashBaseHostType } from "../types/OpenCvSharp/ImgHash/ImgHashBase";
import type { MarrHildrethHashHostType } from "../types/OpenCvSharp/ImgHash/MarrHildrethHash";
import type { PHashHostType } from "../types/OpenCvSharp/ImgHash/PHash";
import type { RadialVarianceHashHostType } from "../types/OpenCvSharp/ImgHash/RadialVarianceHash";
import type { ImreadModesHostType } from "../types/OpenCvSharp/ImreadModes";
import type { ImwriteEXRTypeFlagsHostType } from "../types/OpenCvSharp/ImwriteEXRTypeFlags";
import type { ImwriteFlagsHostType } from "../types/OpenCvSharp/ImwriteFlags";
import type { ImwritePAMFlagsHostType } from "../types/OpenCvSharp/ImwritePAMFlags";
import type { ImwritePNGFlagsHostType } from "../types/OpenCvSharp/ImwritePNGFlags";
import type { InOutArrayKindHostType } from "../types/OpenCvSharp/InOutArrayKind";
import type { InpaintMethodHostType } from "../types/OpenCvSharp/InpaintMethod";
import type { InputArrayHostType } from "../types/OpenCvSharp/InputArray";
import type { InputOutputArrayHostType } from "../types/OpenCvSharp/InputOutputArray";
import type { ExceptionHandlerHostType } from "../types/OpenCvSharp/Internal/ExceptionHandler";
import type { ExceptionStatusHostType } from "../types/OpenCvSharp/Internal/ExceptionStatus";
import type { NativeMethodsHostType } from "../types/OpenCvSharp/Internal/NativeMethods";
import type { StdStringHostType } from "../types/OpenCvSharp/Internal/StdString";
import type { ArrayAddress1HostType } from "../types/OpenCvSharp/Internal/Util/ArrayAddress";
import type { ArrayAddress2HostType } from "../types/OpenCvSharp/Internal/Util/ArrayAddress2";
import type { PInvokeHelperHostType } from "../types/OpenCvSharp/Internal/Util/PInvokeHelper";
import type { ReadOnlyArray2DHostType } from "../types/OpenCvSharp/Internal/Util/ReadOnlyArray2D";
import type { SaturateCastHostType } from "../types/OpenCvSharp/Internal/Util/SaturateCast";
import type { ScopedGCHandleHostType } from "../types/OpenCvSharp/Internal/Util/ScopedGCHandle";
import type { IStdVectorHostType } from "../types/OpenCvSharp/Internal/Vectors/IStdVector";
import type { VectorOfByteHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfByte";
import type { VectorOfDMatchHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfDMatch";
import type { VectorOfDTreesNodeHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfDTreesNode";
import type { VectorOfDoubleHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfDouble";
import type { VectorOfFloatHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfFloat";
import type { VectorOfImageFeaturesHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfImageFeatures";
import type { VectorOfInt32HostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfInt32";
import type { VectorOfKeyPointHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfKeyPoint";
import type { VectorOfMatHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfMat";
import type { VectorOfPointHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfPoint";
import type { VectorOfPoint2dHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfPoint2d";
import type { VectorOfPoint2fHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfPoint2f";
import type { VectorOfPoint3fHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfPoint3f";
import type { VectorOfRectHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfRect";
import type { VectorOfRect2dHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfRect2d";
import type { VectorOfRotatedRectHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfRotatedRect";
import type { VectorOfStringHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfString";
import type { VectorOfVec2fHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVec2f";
import type { VectorOfVec3fHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVec3f";
import type { VectorOfVec4fHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVec4f";
import type { VectorOfVec4iHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVec4i";
import type { VectorOfVectorByteHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVectorByte";
import type { VectorOfVectorDMatchHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVectorDMatch";
import type { VectorOfVectorDoubleHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVectorDouble";
import type { VectorOfVectorInt32HostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVectorInt32";
import type { VectorOfVectorKeyPointHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVectorKeyPoint";
import type { VectorOfVectorPointHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVectorPoint";
import type { VectorOfVectorPoint2fHostType } from "../types/OpenCvSharp/Internal/Vectors/VectorOfVectorPoint2f";
import type { Win32ApiHostType } from "../types/OpenCvSharp/Internal/Win32API";
import type { WindowsLibraryLoaderHostType } from "../types/OpenCvSharp/Internal/WindowsLibraryLoader";
import type { InterpolationFlagsHostType } from "../types/OpenCvSharp/InterpolationFlags";
import type { KAZEHostType } from "../types/OpenCvSharp/KAZE";
import type { KAZEDiffusivityTypeHostType } from "../types/OpenCvSharp/KAZEDiffusivityType";
import type { KMeansFlagsHostType } from "../types/OpenCvSharp/KMeansFlags";
import type { KalmanFilterHostType } from "../types/OpenCvSharp/KalmanFilter";
import type { KeyPointHostType } from "../types/OpenCvSharp/KeyPoint";
import type { KeyPointsFilterHostType } from "../types/OpenCvSharp/KeyPointsFilter";
import type { LDAHostType } from "../types/OpenCvSharp/LDA";
import type { Line2DHostType } from "../types/OpenCvSharp/Line2D";
import type { Line3DHostType } from "../types/OpenCvSharp/Line3D";
import type { KeyLineHostType } from "../types/OpenCvSharp/LineDescriptor/KeyLine";
import type { LSDParamHostType } from "../types/OpenCvSharp/LineDescriptor/LSDParam";
import type { LineIteratorHostType } from "../types/OpenCvSharp/LineIterator";
import type { LineSegmentDetectorHostType } from "../types/OpenCvSharp/LineSegmentDetector";
import type { LineSegmentDetectorModesHostType } from "../types/OpenCvSharp/LineSegmentDetectorModes";
import type { LineSegmentPointHostType } from "../types/OpenCvSharp/LineSegmentPoint";
import type { LineSegmentPolarHostType } from "../types/OpenCvSharp/LineSegmentPolar";
import type { LineTypesHostType } from "../types/OpenCvSharp/LineTypes";
import type { LogLevelHostType } from "../types/OpenCvSharp/LogLevel";
import type { ANN_MLPHostType } from "../types/OpenCvSharp/ML/ANN_MLP";
import type { BoostHostType } from "../types/OpenCvSharp/ML/Boost";
import type { DTreesHostType } from "../types/OpenCvSharp/ML/DTrees";
import type { KNearestHostType } from "../types/OpenCvSharp/ML/KNearest";
import type { LogisticRegressionHostType } from "../types/OpenCvSharp/ML/LogisticRegression";
import type { NormalBayesClassifierHostType } from "../types/OpenCvSharp/ML/NormalBayesClassifier";
import type { ParamGridHostType } from "../types/OpenCvSharp/ML/ParamGrid";
import type { RTreesHostType } from "../types/OpenCvSharp/ML/RTrees";
import type { SVMHostType } from "../types/OpenCvSharp/ML/SVM";
import type { SampleTypesHostType } from "../types/OpenCvSharp/ML/SampleTypes";
import type { StatModelHostType } from "../types/OpenCvSharp/ML/StatModel";
import type { TrainDataHostType } from "../types/OpenCvSharp/ML/TrainData";
import type { MSERHostType } from "../types/OpenCvSharp/MSER";
import type { MarkerTypesHostType } from "../types/OpenCvSharp/MarkerTypes";
import type { MatHostType } from "../types/OpenCvSharp/Mat";
import type { MatDiagTypeHostType } from "../types/OpenCvSharp/MatDiagType";
import type { MatExprHostType } from "../types/OpenCvSharp/MatExpr";
import type { MatExprRowColIndexerHostType } from "../types/OpenCvSharp/MatExprRowColIndexer";
import type { MatForeachFunctionByteHostType } from "../types/OpenCvSharp/MatForeachFunctionByte";
import type { MatForeachFunctionDoubleHostType } from "../types/OpenCvSharp/MatForeachFunctionDouble";
import type { MatForeachFunctionFloatHostType } from "../types/OpenCvSharp/MatForeachFunctionFloat";
import type { MatForeachFunctionInt16HostType } from "../types/OpenCvSharp/MatForeachFunctionInt16";
import type { MatForeachFunctionInt32HostType } from "../types/OpenCvSharp/MatForeachFunctionInt32";
import type { MatForeachFunctionVec2bHostType } from "../types/OpenCvSharp/MatForeachFunctionVec2b";
import type { MatForeachFunctionVec2dHostType } from "../types/OpenCvSharp/MatForeachFunctionVec2d";
import type { MatForeachFunctionVec2fHostType } from "../types/OpenCvSharp/MatForeachFunctionVec2f";
import type { MatForeachFunctionVec2iHostType } from "../types/OpenCvSharp/MatForeachFunctionVec2i";
import type { MatForeachFunctionVec2sHostType } from "../types/OpenCvSharp/MatForeachFunctionVec2s";
import type { MatForeachFunctionVec3bHostType } from "../types/OpenCvSharp/MatForeachFunctionVec3b";
import type { MatForeachFunctionVec3dHostType } from "../types/OpenCvSharp/MatForeachFunctionVec3d";
import type { MatForeachFunctionVec3fHostType } from "../types/OpenCvSharp/MatForeachFunctionVec3f";
import type { MatForeachFunctionVec3iHostType } from "../types/OpenCvSharp/MatForeachFunctionVec3i";
import type { MatForeachFunctionVec3sHostType } from "../types/OpenCvSharp/MatForeachFunctionVec3s";
import type { MatForeachFunctionVec4bHostType } from "../types/OpenCvSharp/MatForeachFunctionVec4b";
import type { MatForeachFunctionVec4dHostType } from "../types/OpenCvSharp/MatForeachFunctionVec4d";
import type { MatForeachFunctionVec4fHostType } from "../types/OpenCvSharp/MatForeachFunctionVec4f";
import type { MatForeachFunctionVec4iHostType } from "../types/OpenCvSharp/MatForeachFunctionVec4i";
import type { MatForeachFunctionVec4sHostType } from "../types/OpenCvSharp/MatForeachFunctionVec4s";
import type { MatForeachFunctionVec6bHostType } from "../types/OpenCvSharp/MatForeachFunctionVec6b";
import type { MatForeachFunctionVec6dHostType } from "../types/OpenCvSharp/MatForeachFunctionVec6d";
import type { MatForeachFunctionVec6fHostType } from "../types/OpenCvSharp/MatForeachFunctionVec6f";
import type { MatForeachFunctionVec6iHostType } from "../types/OpenCvSharp/MatForeachFunctionVec6i";
import type { MatForeachFunctionVec6sHostType } from "../types/OpenCvSharp/MatForeachFunctionVec6s";
import type { MatIndexerHostType } from "../types/OpenCvSharp/MatIndexer";
import type { MatMemoryManagerHostType } from "../types/OpenCvSharp/MatMemoryManager";
import type { MatTypeHostType } from "../types/OpenCvSharp/MatType";
import type { MergeDebevecHostType } from "../types/OpenCvSharp/MergeDebevec";
import type { MergeExposuresHostType } from "../types/OpenCvSharp/MergeExposures";
import type { MergeMertensHostType } from "../types/OpenCvSharp/MergeMertens";
import type { MomentsHostType } from "../types/OpenCvSharp/Moments";
import type { MorphShapesHostType } from "../types/OpenCvSharp/MorphShapes";
import type { MorphTypesHostType } from "../types/OpenCvSharp/MorphTypes";
import type { MotionTypesHostType } from "../types/OpenCvSharp/MotionTypes";
import type { MouseCallbackHostType } from "../types/OpenCvSharp/MouseCallback";
import type { MouseEventFlagsHostType } from "../types/OpenCvSharp/MouseEventFlags";
import type { MouseEventTypesHostType } from "../types/OpenCvSharp/MouseEventTypes";
import type { NormTypesHostType } from "../types/OpenCvSharp/NormTypes";
import type { ORBHostType } from "../types/OpenCvSharp/ORB";
import type { ORBScoreTypeHostType } from "../types/OpenCvSharp/ORBScoreType";
import type { OpenCVExceptionHostType } from "../types/OpenCvSharp/OpenCVException";
import type { OpenCvSharpExceptionHostType } from "../types/OpenCvSharp/OpenCvSharpException";
import type { CvOptFlowHostType } from "../types/OpenCvSharp/OptFlow/CvOptFlow";
import type { OpticalFlowFlagsHostType } from "../types/OpenCvSharp/OpticalFlowFlags";
import type { OutputArrayHostType } from "../types/OpenCvSharp/OutputArray";
import type { OutputArrayOfMatListHostType } from "../types/OpenCvSharp/OutputArrayOfMatList";
import type { OutputArrayOfStructListHostType } from "../types/OpenCvSharp/OutputArrayOfStructList";
import type { PCAHostType } from "../types/OpenCvSharp/PCA";
import type { PixelConnectivityHostType } from "../types/OpenCvSharp/PixelConnectivity";
import type { PointHostType } from "../types/OpenCvSharp/Point";
import type { Point2dHostType } from "../types/OpenCvSharp/Point2d";
import type { Point2fHostType } from "../types/OpenCvSharp/Point2f";
import type { Point3dHostType } from "../types/OpenCvSharp/Point3d";
import type { Point3fHostType } from "../types/OpenCvSharp/Point3f";
import type { Point3iHostType } from "../types/OpenCvSharp/Point3i";
import type { ProjectionTypeHostType } from "../types/OpenCvSharp/ProjectionType";
import type { PtrHostType } from "../types/OpenCvSharp/Ptr";
import type { PyrLKOpticalFlowHostType } from "../types/OpenCvSharp/PyrLKOpticalFlow";
import type { QRCodeDetectorHostType } from "../types/OpenCvSharp/QRCodeDetector";
import type { QualityBRISQUEHostType } from "../types/OpenCvSharp/Quality/QualityBRISQUE";
import type { QualityBaseHostType } from "../types/OpenCvSharp/Quality/QualityBase";
import type { QualityGMSDHostType } from "../types/OpenCvSharp/Quality/QualityGMSD";
import type { QualityMSEHostType } from "../types/OpenCvSharp/Quality/QualityMSE";
import type { QualityPSNRHostType } from "../types/OpenCvSharp/Quality/QualityPSNR";
import type { QualitySSIMHostType } from "../types/OpenCvSharp/Quality/QualitySSIM";
import type { RNGHostType } from "../types/OpenCvSharp/RNG";
import type { RNG_MT19937HostType } from "../types/OpenCvSharp/RNG_MT19937";
import type { RangeHostType } from "../types/OpenCvSharp/Range";
import type { RangefHostType } from "../types/OpenCvSharp/Rangef";
import type { RectHostType } from "../types/OpenCvSharp/Rect";
import type { Rect2dHostType } from "../types/OpenCvSharp/Rect2d";
import type { Rect2fHostType } from "../types/OpenCvSharp/Rect2f";
import type { RectanglesIntersectTypesHostType } from "../types/OpenCvSharp/RectanglesIntersectTypes";
import type { ReduceDimensionHostType } from "../types/OpenCvSharp/ReduceDimension";
import type { ReduceTypesHostType } from "../types/OpenCvSharp/ReduceTypes";
import type { ResourcesTrackerHostType } from "../types/OpenCvSharp/ResourcesTracker";
import type { RetrievalModesHostType } from "../types/OpenCvSharp/RetrievalModes";
import type { RidgeDetectionFilterHostType } from "../types/OpenCvSharp/RidgeDetectionFilter";
import type { RobotWorldHandEyeCalibrationMethodHostType } from "../types/OpenCvSharp/RobotWorldHandEyeCalibrationMethod";
import type { RobustEstimationAlgorithmsHostType } from "../types/OpenCvSharp/RobustEstimationAlgorithms";
import type { RotateFlagsHostType } from "../types/OpenCvSharp/RotateFlags";
import type { RotatedRectHostType } from "../types/OpenCvSharp/RotatedRect";
import type { SVDHostType } from "../types/OpenCvSharp/SVD";
import type { ScalarHostType } from "../types/OpenCvSharp/Scalar";
import type { SeamlessCloneMethodsHostType } from "../types/OpenCvSharp/SeamlessCloneMethods";
import type { IntelligentScissorsMBHostType } from "../types/OpenCvSharp/Segmentation/IntelligentScissorsMB";
import type { ShapeContextDistanceExtractorHostType } from "../types/OpenCvSharp/ShapeContextDistanceExtractor";
import type { ShapeDistanceExtractorHostType } from "../types/OpenCvSharp/ShapeDistanceExtractor";
import type { ShapeMatchModesHostType } from "../types/OpenCvSharp/ShapeMatchModes";
import type { SimilarRectsHostType } from "../types/OpenCvSharp/SimilarRects";
import type { SimpleBlobDetectorHostType } from "../types/OpenCvSharp/SimpleBlobDetector";
import type { SizeHostType } from "../types/OpenCvSharp/Size";
import type { Size2dHostType } from "../types/OpenCvSharp/Size2d";
import type { Size2fHostType } from "../types/OpenCvSharp/Size2f";
import type { SolveLPResultHostType } from "../types/OpenCvSharp/SolveLPResult";
import type { SolvePnPFlagsHostType } from "../types/OpenCvSharp/SolvePnPFlags";
import type { SortFlagsHostType } from "../types/OpenCvSharp/SortFlags";
import type { SparseMatHostType } from "../types/OpenCvSharp/SparseMat";
import type { SparseMatIndexerHostType } from "../types/OpenCvSharp/SparseMatIndexer";
import type { StereoBMHostType } from "../types/OpenCvSharp/StereoBM";
import type { StereoMatcherHostType } from "../types/OpenCvSharp/StereoMatcher";
import type { StereoRectificationFlagsHostType } from "../types/OpenCvSharp/StereoRectificationFlags";
import type { StereoSGBMHostType } from "../types/OpenCvSharp/StereoSGBM";
import type { StereoSGBMModeHostType } from "../types/OpenCvSharp/StereoSGBM";
import type { StitcherHostType } from "../types/OpenCvSharp/Stitcher";
import type { NextEdgeTypeHostType } from "../types/OpenCvSharp/Subdiv2D";
import type { Subdiv2DHostType } from "../types/OpenCvSharp/Subdiv2D";
import type { SuperResolutionHostType } from "../types/OpenCvSharp/SuperResolution";
import type { TemplateMatchModesHostType } from "../types/OpenCvSharp/TemplateMatchModes";
import type { TermCriteriaHostType } from "../types/OpenCvSharp/TermCriteria";
import type { BaseOCRHostType } from "../types/OpenCvSharp/Text/BaseOCR";
import type { ComponentLevelsHostType } from "../types/OpenCvSharp/Text/ComponentLevels";
import type { CvTextHostType } from "../types/OpenCvSharp/Text/CvText";
import type { OCRTesseractHostType } from "../types/OpenCvSharp/Text/OCRTesseract";
import type { TextDetectorHostType } from "../types/OpenCvSharp/TextDetector";
import type { TextDetectorCNNHostType } from "../types/OpenCvSharp/TextDetectorCNN";
import type { ThresholdTypesHostType } from "../types/OpenCvSharp/ThresholdTypes";
import type { TonemapHostType } from "../types/OpenCvSharp/Tonemap";
import type { TonemapDragoHostType } from "../types/OpenCvSharp/TonemapDrago";
import type { TonemapMantiukHostType } from "../types/OpenCvSharp/TonemapMantiuk";
import type { TonemapReinhardHostType } from "../types/OpenCvSharp/TonemapReinhard";
import type { TrackbarCallbackHostType } from "../types/OpenCvSharp/TrackbarCallback";
import type { TrackbarCallbackNativeHostType } from "../types/OpenCvSharp/TrackbarCallbackNative";
import type { TrackerHostType } from "../types/OpenCvSharp/Tracker";
import type { TrackerGOTURNHostType } from "../types/OpenCvSharp/TrackerGOTURN";
import type { TrackerMILHostType } from "../types/OpenCvSharp/TrackerMIL";
import type { TrackerCSRTHostType } from "../types/OpenCvSharp/Tracking/TrackerCSRT";
import type { TrackerKCFHostType } from "../types/OpenCvSharp/Tracking/TrackerKCF";
import type { TrackerTypesHostType } from "../types/OpenCvSharp/Tracking/TrackerTypes";
import type { UMatHostType } from "../types/OpenCvSharp/UMat";
import type { UMatUsageFlagsHostType } from "../types/OpenCvSharp/UMatUsageFlags";
import type { LocalOptimMethodHostType } from "../types/OpenCvSharp/UsacParams";
import type { NeighborSearchMethodHostType } from "../types/OpenCvSharp/UsacParams";
import type { SamplingMethodHostType } from "../types/OpenCvSharp/UsacParams";
import type { ScoreMethodHostType } from "../types/OpenCvSharp/UsacParams";
import type { UsacParamsHostType } from "../types/OpenCvSharp/UsacParams";
import type { WUsacParamsHostType } from "../types/OpenCvSharp/UsacParams";
import type { Vec2bHostType } from "../types/OpenCvSharp/Vec2b";
import type { Vec2dHostType } from "../types/OpenCvSharp/Vec2d";
import type { Vec2fHostType } from "../types/OpenCvSharp/Vec2f";
import type { Vec2iHostType } from "../types/OpenCvSharp/Vec2i";
import type { Vec2sHostType } from "../types/OpenCvSharp/Vec2s";
import type { Vec2wHostType } from "../types/OpenCvSharp/Vec2w";
import type { Vec3bHostType } from "../types/OpenCvSharp/Vec3b";
import type { Vec3dHostType } from "../types/OpenCvSharp/Vec3d";
import type { Vec3fHostType } from "../types/OpenCvSharp/Vec3f";
import type { Vec3iHostType } from "../types/OpenCvSharp/Vec3i";
import type { Vec3sHostType } from "../types/OpenCvSharp/Vec3s";
import type { Vec3wHostType } from "../types/OpenCvSharp/Vec3w";
import type { Vec4bHostType } from "../types/OpenCvSharp/Vec4b";
import type { Vec4dHostType } from "../types/OpenCvSharp/Vec4d";
import type { Vec4fHostType } from "../types/OpenCvSharp/Vec4f";
import type { Vec4iHostType } from "../types/OpenCvSharp/Vec4i";
import type { Vec4sHostType } from "../types/OpenCvSharp/Vec4s";
import type { Vec4wHostType } from "../types/OpenCvSharp/Vec4w";
import type { Vec6bHostType } from "../types/OpenCvSharp/Vec6b";
import type { Vec6dHostType } from "../types/OpenCvSharp/Vec6d";
import type { Vec6fHostType } from "../types/OpenCvSharp/Vec6f";
import type { Vec6iHostType } from "../types/OpenCvSharp/Vec6i";
import type { Vec6sHostType } from "../types/OpenCvSharp/Vec6s";
import type { Vec6wHostType } from "../types/OpenCvSharp/Vec6w";
import type { VideoAccelerationTypeHostType } from "../types/OpenCvSharp/VideoAccelerationType";
import type { VideoCaptureHostType } from "../types/OpenCvSharp/VideoCapture";
import type { VideoCaptureAPIsHostType } from "../types/OpenCvSharp/VideoCaptureAPIs";
import type { VideoCaptureParaHostType } from "../types/OpenCvSharp/VideoCapturePara";
import type { VideoCapturePropertiesHostType } from "../types/OpenCvSharp/VideoCaptureProperties";
import type { VideoWriterHostType } from "../types/OpenCvSharp/VideoWriter";
import type { VideoWriterParaHostType } from "../types/OpenCvSharp/VideoWriterPara";
import type { VideoWriterPropertiesHostType } from "../types/OpenCvSharp/VideoWriterProperties";
import type { WarpPolarModeHostType } from "../types/OpenCvSharp/WarpPolarMode";
import type { WeChatQRCodeHostType } from "../types/OpenCvSharp/WeChatQRCode";
import type { WindowHostType } from "../types/OpenCvSharp/Window";
import type { WindowFlagsHostType } from "../types/OpenCvSharp/WindowFlags";
import type { WindowPropertyFlagsHostType } from "../types/OpenCvSharp/WindowPropertyFlags";
import type { BriefDescriptorExtractorHostType } from "../types/OpenCvSharp/XFeatures2D/BriefDescriptorExtractor";
import type { FREAKHostType } from "../types/OpenCvSharp/XFeatures2D/FREAK";
import type { LATCHHostType } from "../types/OpenCvSharp/XFeatures2D/LATCH";
import type { LUCIDHostType } from "../types/OpenCvSharp/XFeatures2D/LUCID";
import type { SURFHostType } from "../types/OpenCvSharp/XFeatures2D/SURF";
import type { StarDetectorHostType } from "../types/OpenCvSharp/XFeatures2D/StarDetector";
import type { AdaptiveManifoldFilterHostType } from "../types/OpenCvSharp/XImgProc/AdaptiveManifoldFilter";
import type { AngleRangeOptionHostType } from "../types/OpenCvSharp/XImgProc/AngleRangeOption";
import type { CvXImgProcHostType } from "../types/OpenCvSharp/XImgProc/CvXImgProc";
import type { DTFilterHostType } from "../types/OpenCvSharp/XImgProc/DTFilter";
import type { EdgeAwareFiltersListHostType } from "../types/OpenCvSharp/XImgProc/EdgeAwareFiltersList";
import type { EdgeBoxesHostType } from "../types/OpenCvSharp/XImgProc/EdgeBoxes";
import type { FastBilateralSolverFilterHostType } from "../types/OpenCvSharp/XImgProc/FastBilateralSolverFilter";
import type { FastGlobalSmootherFilterHostType } from "../types/OpenCvSharp/XImgProc/FastGlobalSmootherFilter";
import type { FastLineDetectorHostType } from "../types/OpenCvSharp/XImgProc/FastLineDetector";
import type { GuidedFilterHostType } from "../types/OpenCvSharp/XImgProc/GuidedFilter";
import type { HoughDeskewOptionHostType } from "../types/OpenCvSharp/XImgProc/HoughDeskewOption";
import type { HoughOPHostType } from "../types/OpenCvSharp/XImgProc/HoughOP";
import type { LocalBinarizationMethodsHostType } from "../types/OpenCvSharp/XImgProc/LocalBinarizationMethods";
import type { RFFeatureGetterHostType } from "../types/OpenCvSharp/XImgProc/RFFeatureGetter";
import type { RulesOptionHostType } from "../types/OpenCvSharp/XImgProc/RulesOption";
import type { SLICTypeHostType } from "../types/OpenCvSharp/XImgProc/SLICType";
import type { GraphSegmentationHostType } from "../types/OpenCvSharp/XImgProc/Segmentation/GraphSegmentation";
import type { SelectiveSearchSegmentationHostType } from "../types/OpenCvSharp/XImgProc/Segmentation/SelectiveSearchSegmentation";
import type { SelectiveSearchSegmentationStrategyColorHostType } from "../types/OpenCvSharp/XImgProc/Segmentation/SelectiveSearchSegmentationStrategy";
import type { SelectiveSearchSegmentationStrategyFillHostType } from "../types/OpenCvSharp/XImgProc/Segmentation/SelectiveSearchSegmentationStrategy";
import type { SelectiveSearchSegmentationStrategyHostType } from "../types/OpenCvSharp/XImgProc/Segmentation/SelectiveSearchSegmentationStrategy";
import type { SelectiveSearchSegmentationStrategySizeHostType } from "../types/OpenCvSharp/XImgProc/Segmentation/SelectiveSearchSegmentationStrategy";
import type { SelectiveSearchSegmentationStrategyTextureHostType } from "../types/OpenCvSharp/XImgProc/Segmentation/SelectiveSearchSegmentationStrategy";
import type { SelectiveSearchSegmentationStrategyMultipleHostType } from "../types/OpenCvSharp/XImgProc/Segmentation/SelectiveSearchSegmentationStrategyMultiple";
import type { StructuredEdgeDetectionHostType } from "../types/OpenCvSharp/XImgProc/StructuredEdgeDetection";
import type { SuperpixelLSCHostType } from "../types/OpenCvSharp/XImgProc/SuperpixelLSC";
import type { SuperpixelSEEDSHostType } from "../types/OpenCvSharp/XImgProc/SuperpixelSEEDS";
import type { SuperpixelSLICHostType } from "../types/OpenCvSharp/XImgProc/SuperpixelSLIC";
import type { ThinningTypesHostType } from "../types/OpenCvSharp/XImgProc/ThinningTypes";
import type { WMFWeightTypeHostType } from "../types/OpenCvSharp/XImgProc/WMFWeightType";
import type { Bm3dStepsHostType } from "../types/OpenCvSharp/XPhoto/Bm3dSteps";
import type { CvXPhotoHostType } from "../types/OpenCvSharp/XPhoto/CvXPhoto";
import type { GrayworldWBHostType } from "../types/OpenCvSharp/XPhoto/GrayworldWB";
import type { InpaintTypesHostType } from "../types/OpenCvSharp/XPhoto/InpaintTypes";
import type { LearningBasedWBHostType } from "../types/OpenCvSharp/XPhoto/LearningBasedWB";
import type { SimpleWBHostType } from "../types/OpenCvSharp/XPhoto/SimpleWB";
import type { TonemapDurandHostType } from "../types/OpenCvSharp/XPhoto/TonemapDurand";
import type { TransformTypesHostType } from "../types/OpenCvSharp/XPhoto/TransformTypes";
import type { WhiteBalancerHostType } from "../types/OpenCvSharp/XPhoto/WhiteBalancer";

type OpenCvSharpCollection = HostTypeCollection & {
  readonly OpenCvSharp: OpenCvSharpRoot;
};

type OpenCvSharpRoot = PropertyBag & {
  readonly Aruco: OpenCvSharpRoot_Aruco;
  readonly Detail: OpenCvSharpRoot_Detail;
  readonly Dnn: OpenCvSharpRoot_Dnn;
  readonly DnnSuperres: OpenCvSharpRoot_DnnSuperres;
  readonly Face: OpenCvSharpRoot_Face;
  readonly Features2D: OpenCvSharpRoot_Features2D;
  readonly Flann: OpenCvSharpRoot_Flann;
  readonly ImgHash: OpenCvSharpRoot_ImgHash;
  readonly Internal: OpenCvSharpRoot_Internal;
  readonly LineDescriptor: OpenCvSharpRoot_LineDescriptor;
  readonly ML: OpenCvSharpRoot_ML;
  readonly OptFlow: OpenCvSharpRoot_OptFlow;
  readonly Quality: OpenCvSharpRoot_Quality;
  readonly Segmentation: OpenCvSharpRoot_Segmentation;
  readonly Text: OpenCvSharpRoot_Text;
  readonly Tracking: OpenCvSharpRoot_Tracking;
  readonly XFeatures2D: OpenCvSharpRoot_XFeatures2D;
  readonly XImgProc: OpenCvSharpRoot_XImgProc;
  readonly XPhoto: OpenCvSharpRoot_XPhoto;
  readonly AKAZE: AKAZEHostType;
  readonly AKAZEDescriptorType: AKAZEDescriptorTypeHostType;
  readonly AccessFlag: AccessFlagHostType;
  readonly AdaptiveThresholdTypes: AdaptiveThresholdTypesHostType;
  readonly AgastFeatureDetector: AgastFeatureDetectorHostType;
  readonly Algorithm: AlgorithmHostType;
  readonly AlgorithmParamType: AlgorithmParamTypeHostType;
  readonly BFMatcher: BFMatcherHostType;
  readonly BOWImgDescriptorExtractor: BOWImgDescriptorExtractorHostType;
  readonly BOWKMeansTrainer: BOWKMeansTrainerHostType;
  readonly BOWTrainer: BOWTrainerHostType;
  readonly BRISK: BRISKHostType;
  readonly BackgroundSubtractor: BackgroundSubtractorHostType;
  readonly BackgroundSubtractorGMG: BackgroundSubtractorGMGHostType;
  readonly BackgroundSubtractorKNN: BackgroundSubtractorKNNHostType;
  readonly BackgroundSubtractorMOG: BackgroundSubtractorMOGHostType;
  readonly BackgroundSubtractorMOG2: BackgroundSubtractorMOG2HostType;
  readonly BorderTypes: BorderTypesHostType;
  readonly BroxOpticalFlow: BroxOpticalFlowHostType;
  readonly ButtonType: ButtonTypeHostType;
  readonly CLAHE: CLAHEHostType;
  readonly CalibrateCRF: CalibrateCRFHostType;
  readonly CalibrateDebevec: CalibrateDebevecHostType;
  readonly CalibrateRobertson: CalibrateRobertsonHostType;
  readonly CalibrationFlags: CalibrationFlagsHostType;
  readonly CameraChannels: CameraChannelsHostType;
  readonly CapturePosAviRatio: CapturePosAviRatioHostType;
  readonly CaptureType: CaptureTypeHostType;
  readonly CascadeClassifier: CascadeClassifierHostType;
  readonly ChessboardFlags: ChessboardFlagsHostType;
  readonly CircleSegment: CircleSegmentHostType;
  readonly CmpType: CmpTypeHostType;
  readonly ColorConversionCodes: ColorConversionCodesHostType;
  readonly ColormapTypes: ColormapTypesHostType;
  readonly ConnectedComponents: ConnectedComponentsHostType;
  readonly ConnectedComponentsAlgorithmsTypes: ConnectedComponentsAlgorithmsTypesHostType;
  readonly ConnectedComponentsTypes: ConnectedComponentsTypesHostType;
  readonly ContourApproximationModes: ContourApproximationModesHostType;
  readonly ConvertImageModes: ConvertImageModesHostType;
  readonly CovarFlags: CovarFlagsHostType;
  readonly CpuFeatures: CpuFeaturesHostType;
  readonly CriteriaTypes: CriteriaTypesHostType;
  readonly Cv2: Cv2HostType;
  readonly CvErrorCallback: CvErrorCallbackHostType;
  readonly CvObject: CvObjectHostType;
  readonly CvTrackbar: CvTrackbarHostType;
  readonly DMatch: DMatchHostType;
  readonly DctFlags: DctFlagsHostType;
  readonly DecompTypes: DecompTypesHostType;
  readonly DenseOpticalFlowExt: DenseOpticalFlowExtHostType;
  readonly DescriptorMatcher: DescriptorMatcherHostType;
  readonly DetectionROI: DetectionROIHostType;
  readonly DftFlags: DftFlagsHostType;
  readonly DisposableCvObject: DisposableCvObjectHostType;
  readonly DisposableObject: DisposableObjectHostType;
  readonly DistanceTransformLabelTypes: DistanceTransformLabelTypesHostType;
  readonly DistanceTransformMasks: DistanceTransformMasksHostType;
  readonly DistanceTypes: DistanceTypesHostType;
  readonly DistributionType: DistributionTypeHostType;
  readonly DrawMatchesFlags: DrawMatchesFlagsHostType;
  readonly DualTVL1OpticalFlow: DualTVL1OpticalFlowHostType;
  readonly EM: EMHostType;
  readonly EMStartStep: EMStartStepHostType;
  readonly EMTypes: EMTypesHostType;
  readonly EdgePreservingMethods: EdgePreservingMethodsHostType;
  readonly ErrorCode: ErrorCodeHostType;
  readonly EssentialMatMethod: EssentialMatMethodHostType;
  readonly FASTType: FASTTypeHostType;
  readonly FarnebackOpticalFlow: FarnebackOpticalFlowHostType;
  readonly FastFeatureDetector: FastFeatureDetectorHostType;
  readonly Feature2D: Feature2DHostType;
  readonly FileNode: FileNodeHostType;
  readonly FileNodeIterator: FileNodeIteratorHostType;
  readonly FileStorage: FileStorageHostType;
  readonly FindCirclesGridFlags: FindCirclesGridFlagsHostType;
  readonly FishEyeCalibrationFlags: FishEyeCalibrationFlagsHostType;
  readonly FlannBasedMatcher: FlannBasedMatcherHostType;
  readonly FlipMode: FlipModeHostType;
  readonly FloodFillFlags: FloodFillFlagsHostType;
  readonly FormatType: FormatTypeHostType;
  readonly FourCC: FourCCHostType;
  readonly FrameSource: FrameSourceHostType;
  readonly FundamentalMatMethods: FundamentalMatMethodsHostType;
  readonly GFTTDetector: GFTTDetectorHostType;
  readonly GemmFlags: GemmFlagsHostType;
  readonly GeneralizedHough: GeneralizedHoughHostType;
  readonly GeneralizedHoughBallard: GeneralizedHoughBallardHostType;
  readonly GeneralizedHoughGuil: GeneralizedHoughGuilHostType;
  readonly GrabCutClasses: GrabCutClassesHostType;
  readonly GrabCutModes: GrabCutModesHostType;
  readonly HOGDescriptor: HOGDescriptorHostType;
  readonly HaarDetectionTypes: HaarDetectionTypesHostType;
  readonly HandEyeCalibrationMethod: HandEyeCalibrationMethodHostType;
  readonly HausdorffDistanceExtractor: HausdorffDistanceExtractorHostType;
  readonly HersheyFonts: HersheyFontsHostType;
  readonly HierarchyIndex: HierarchyIndexHostType;
  readonly HistCompMethods: HistCompMethodsHostType;
  readonly HistogramNormType: HistogramNormTypeHostType;
  readonly HomographyMethods: HomographyMethodsHostType;
  readonly HoughModes: HoughModesHostType;
  readonly ICvPtrHolder: ICvPtrHolderHostType;
  readonly IVec: IVecHostType;
  readonly ImageEncodingParam: ImageEncodingParamHostType;
  readonly ImreadModes: ImreadModesHostType;
  readonly ImwriteEXRTypeFlags: ImwriteEXRTypeFlagsHostType;
  readonly ImwriteFlags: ImwriteFlagsHostType;
  readonly ImwritePAMFlags: ImwritePAMFlagsHostType;
  readonly ImwritePNGFlags: ImwritePNGFlagsHostType;
  readonly InOutArrayKind: InOutArrayKindHostType;
  readonly InpaintMethod: InpaintMethodHostType;
  readonly InputArray: InputArrayHostType;
  readonly InputOutputArray: InputOutputArrayHostType;
  readonly InterpolationFlags: InterpolationFlagsHostType;
  readonly KAZE: KAZEHostType;
  readonly KAZEDiffusivityType: KAZEDiffusivityTypeHostType;
  readonly KMeansFlags: KMeansFlagsHostType;
  readonly KalmanFilter: KalmanFilterHostType;
  readonly KeyPoint: KeyPointHostType;
  readonly KeyPointsFilter: KeyPointsFilterHostType;
  readonly LDA: LDAHostType;
  readonly Line2D: Line2DHostType;
  readonly Line3D: Line3DHostType;
  readonly LineIterator: LineIteratorHostType;
  readonly LineSegmentDetector: LineSegmentDetectorHostType;
  readonly LineSegmentDetectorModes: LineSegmentDetectorModesHostType;
  readonly LineSegmentPoint: LineSegmentPointHostType;
  readonly LineSegmentPolar: LineSegmentPolarHostType;
  readonly LineTypes: LineTypesHostType;
  readonly LocalOptimMethod: LocalOptimMethodHostType;
  readonly LogLevel: LogLevelHostType;
  readonly MSER: MSERHostType;
  readonly MarkerTypes: MarkerTypesHostType;
  readonly Mat: MatHostType;
  readonly MatDiagType: MatDiagTypeHostType;
  readonly MatExpr: MatExprHostType;
  readonly MatExprRowColIndexer: MatExprRowColIndexerHostType;
  readonly MatForeachFunctionByte: MatForeachFunctionByteHostType;
  readonly MatForeachFunctionDouble: MatForeachFunctionDoubleHostType;
  readonly MatForeachFunctionFloat: MatForeachFunctionFloatHostType;
  readonly MatForeachFunctionInt16: MatForeachFunctionInt16HostType;
  readonly MatForeachFunctionInt32: MatForeachFunctionInt32HostType;
  readonly MatForeachFunctionVec2b: MatForeachFunctionVec2bHostType;
  readonly MatForeachFunctionVec2d: MatForeachFunctionVec2dHostType;
  readonly MatForeachFunctionVec2f: MatForeachFunctionVec2fHostType;
  readonly MatForeachFunctionVec2i: MatForeachFunctionVec2iHostType;
  readonly MatForeachFunctionVec2s: MatForeachFunctionVec2sHostType;
  readonly MatForeachFunctionVec3b: MatForeachFunctionVec3bHostType;
  readonly MatForeachFunctionVec3d: MatForeachFunctionVec3dHostType;
  readonly MatForeachFunctionVec3f: MatForeachFunctionVec3fHostType;
  readonly MatForeachFunctionVec3i: MatForeachFunctionVec3iHostType;
  readonly MatForeachFunctionVec3s: MatForeachFunctionVec3sHostType;
  readonly MatForeachFunctionVec4b: MatForeachFunctionVec4bHostType;
  readonly MatForeachFunctionVec4d: MatForeachFunctionVec4dHostType;
  readonly MatForeachFunctionVec4f: MatForeachFunctionVec4fHostType;
  readonly MatForeachFunctionVec4i: MatForeachFunctionVec4iHostType;
  readonly MatForeachFunctionVec4s: MatForeachFunctionVec4sHostType;
  readonly MatForeachFunctionVec6b: MatForeachFunctionVec6bHostType;
  readonly MatForeachFunctionVec6d: MatForeachFunctionVec6dHostType;
  readonly MatForeachFunctionVec6f: MatForeachFunctionVec6fHostType;
  readonly MatForeachFunctionVec6i: MatForeachFunctionVec6iHostType;
  readonly MatForeachFunctionVec6s: MatForeachFunctionVec6sHostType;
  readonly MatIndexer: MatIndexerHostType<any>;
  readonly MatMemoryManager: MatMemoryManagerHostType<any>;
  readonly MatType: MatTypeHostType;
  readonly MergeDebevec: MergeDebevecHostType;
  readonly MergeExposures: MergeExposuresHostType;
  readonly MergeMertens: MergeMertensHostType;
  readonly Moments: MomentsHostType;
  readonly MorphShapes: MorphShapesHostType;
  readonly MorphTypes: MorphTypesHostType;
  readonly MotionTypes: MotionTypesHostType;
  readonly MouseCallback: MouseCallbackHostType;
  readonly MouseEventFlags: MouseEventFlagsHostType;
  readonly MouseEventTypes: MouseEventTypesHostType;
  readonly NeighborSearchMethod: NeighborSearchMethodHostType;
  readonly NextEdgeType: NextEdgeTypeHostType;
  readonly NormTypes: NormTypesHostType;
  readonly ORB: ORBHostType;
  readonly ORBScoreType: ORBScoreTypeHostType;
  readonly OpenCVException: OpenCVExceptionHostType;
  readonly OpenCvSharpException: OpenCvSharpExceptionHostType;
  readonly OpticalFlowFlags: OpticalFlowFlagsHostType;
  readonly OutputArray: OutputArrayHostType;
  readonly OutputArrayOfMatList: OutputArrayOfMatListHostType;
  readonly OutputArrayOfStructList: OutputArrayOfStructListHostType<any>;
  readonly PCA: PCAHostType;
  readonly PixelConnectivity: PixelConnectivityHostType;
  readonly Point: PointHostType;
  readonly Point2d: Point2dHostType;
  readonly Point2f: Point2fHostType;
  readonly Point3d: Point3dHostType;
  readonly Point3f: Point3fHostType;
  readonly Point3i: Point3iHostType;
  readonly ProjectionType: ProjectionTypeHostType;
  readonly Ptr: PtrHostType;
  readonly PyrLKOpticalFlow: PyrLKOpticalFlowHostType;
  readonly QRCodeDetector: QRCodeDetectorHostType;
  readonly RNG: RNGHostType;
  readonly RNG_MT19937: RNG_MT19937HostType;
  readonly Range: RangeHostType;
  readonly Rangef: RangefHostType;
  readonly Rect: RectHostType;
  readonly Rect2d: Rect2dHostType;
  readonly Rect2f: Rect2fHostType;
  readonly RectanglesIntersectTypes: RectanglesIntersectTypesHostType;
  readonly ReduceDimension: ReduceDimensionHostType;
  readonly ReduceTypes: ReduceTypesHostType;
  readonly ResourcesTracker: ResourcesTrackerHostType;
  readonly RetrievalModes: RetrievalModesHostType;
  readonly RidgeDetectionFilter: RidgeDetectionFilterHostType;
  readonly RobotWorldHandEyeCalibrationMethod: RobotWorldHandEyeCalibrationMethodHostType;
  readonly RobustEstimationAlgorithms: RobustEstimationAlgorithmsHostType;
  readonly RotateFlags: RotateFlagsHostType;
  readonly RotatedRect: RotatedRectHostType;
  readonly SVD: SVDHostType;
  readonly SamplingMethod: SamplingMethodHostType;
  readonly Scalar: ScalarHostType;
  readonly ScoreMethod: ScoreMethodHostType;
  readonly SeamlessCloneMethods: SeamlessCloneMethodsHostType;
  readonly ShapeContextDistanceExtractor: ShapeContextDistanceExtractorHostType;
  readonly ShapeDistanceExtractor: ShapeDistanceExtractorHostType;
  readonly ShapeMatchModes: ShapeMatchModesHostType;
  readonly SimilarRects: SimilarRectsHostType;
  readonly SimpleBlobDetector: SimpleBlobDetectorHostType;
  readonly Size: SizeHostType;
  readonly Size2d: Size2dHostType;
  readonly Size2f: Size2fHostType;
  readonly SolveLPResult: SolveLPResultHostType;
  readonly SolvePnPFlags: SolvePnPFlagsHostType;
  readonly SortFlags: SortFlagsHostType;
  readonly SparseMat: SparseMatHostType;
  readonly SparseMatIndexer: SparseMatIndexerHostType<any>;
  readonly StereoBM: StereoBMHostType;
  readonly StereoMatcher: StereoMatcherHostType;
  readonly StereoRectificationFlags: StereoRectificationFlagsHostType;
  readonly StereoSGBM: StereoSGBMHostType;
  readonly StereoSGBMMode: StereoSGBMModeHostType;
  readonly Stitcher: StitcherHostType;
  readonly Subdiv2D: Subdiv2DHostType;
  readonly SuperResolution: SuperResolutionHostType;
  readonly TemplateMatchModes: TemplateMatchModesHostType;
  readonly TermCriteria: TermCriteriaHostType;
  readonly TextDetector: TextDetectorHostType;
  readonly TextDetectorCNN: TextDetectorCNNHostType;
  readonly ThresholdTypes: ThresholdTypesHostType;
  readonly Tonemap: TonemapHostType;
  readonly TonemapDrago: TonemapDragoHostType;
  readonly TonemapMantiuk: TonemapMantiukHostType;
  readonly TonemapReinhard: TonemapReinhardHostType;
  readonly TrackbarCallback: TrackbarCallbackHostType;
  readonly TrackbarCallbackNative: TrackbarCallbackNativeHostType;
  readonly Tracker: TrackerHostType;
  readonly TrackerGOTURN: TrackerGOTURNHostType;
  readonly TrackerMIL: TrackerMILHostType;
  readonly UMat: UMatHostType;
  readonly UMatUsageFlags: UMatUsageFlagsHostType;
  readonly UsacParams: UsacParamsHostType;
  readonly Vec2b: Vec2bHostType;
  readonly Vec2d: Vec2dHostType;
  readonly Vec2f: Vec2fHostType;
  readonly Vec2i: Vec2iHostType;
  readonly Vec2s: Vec2sHostType;
  readonly Vec2w: Vec2wHostType;
  readonly Vec3b: Vec3bHostType;
  readonly Vec3d: Vec3dHostType;
  readonly Vec3f: Vec3fHostType;
  readonly Vec3i: Vec3iHostType;
  readonly Vec3s: Vec3sHostType;
  readonly Vec3w: Vec3wHostType;
  readonly Vec4b: Vec4bHostType;
  readonly Vec4d: Vec4dHostType;
  readonly Vec4f: Vec4fHostType;
  readonly Vec4i: Vec4iHostType;
  readonly Vec4s: Vec4sHostType;
  readonly Vec4w: Vec4wHostType;
  readonly Vec6b: Vec6bHostType;
  readonly Vec6d: Vec6dHostType;
  readonly Vec6f: Vec6fHostType;
  readonly Vec6i: Vec6iHostType;
  readonly Vec6s: Vec6sHostType;
  readonly Vec6w: Vec6wHostType;
  readonly VideoAccelerationType: VideoAccelerationTypeHostType;
  readonly VideoCapture: VideoCaptureHostType;
  readonly VideoCaptureAPIs: VideoCaptureAPIsHostType;
  readonly VideoCapturePara: VideoCaptureParaHostType;
  readonly VideoCaptureProperties: VideoCapturePropertiesHostType;
  readonly VideoWriter: VideoWriterHostType;
  readonly VideoWriterPara: VideoWriterParaHostType;
  readonly VideoWriterProperties: VideoWriterPropertiesHostType;
  readonly WUsacParams: WUsacParamsHostType;
  readonly WarpPolarMode: WarpPolarModeHostType;
  readonly WeChatQRCode: WeChatQRCodeHostType;
  readonly Window: WindowHostType;
  readonly WindowFlags: WindowFlagsHostType;
  readonly WindowPropertyFlags: WindowPropertyFlagsHostType;
};

type OpenCvSharpRoot_Aruco = PropertyBag & {
  readonly CornerRefineMethod: CornerRefineMethodHostType;
  readonly CvAruco: CvArucoHostType;
  readonly DetectorParameters: DetectorParametersHostType;
  readonly Dictionary: DictionaryHostType;
  readonly PredefinedDictionaryName: PredefinedDictionaryNameHostType;
};

type OpenCvSharpRoot_Detail = PropertyBag & {
  readonly AffineBestOf2NearestMatcher: AffineBestOf2NearestMatcherHostType;
  readonly BestOf2NearestMatcher: BestOf2NearestMatcherHostType;
  readonly Blender: BlenderHostType;
  readonly BundleAdjusterBase: BundleAdjusterBaseHostType;
  readonly CameraParams: CameraParamsHostType;
  readonly CvDetail: CvDetailHostType;
  readonly ExposureCompensator: ExposureCompensatorHostType;
  readonly FeaturesFinder: FeaturesFinderHostType;
  readonly FeaturesMatcher: FeaturesMatcherHostType;
  readonly ImageFeatures: ImageFeaturesHostType;
  readonly MatchesInfo: MatchesInfoHostType;
  readonly SeamFinder: SeamFinderHostType;
  readonly WImageFeatures: WImageFeaturesHostType;
  readonly WarperCreator: WarperCreatorHostType;
  readonly WaveCorrectKind: WaveCorrectKindHostType;
};

type OpenCvSharpRoot_Dnn = PropertyBag & {
  readonly Backend: BackendHostType;
  readonly CvDnn: CvDnnHostType;
  readonly Net: NetHostType;
  readonly Target: TargetHostType;
};

type OpenCvSharpRoot_DnnSuperres = PropertyBag & {
  readonly DnnSuperResImpl: DnnSuperResImplHostType;
};

type OpenCvSharpRoot_Face = PropertyBag & {
  readonly BasicFaceRecognizer: BasicFaceRecognizerHostType;
  readonly EigenFaceRecognizer: EigenFaceRecognizerHostType;
  readonly FaceRecognizer: FaceRecognizerHostType;
  readonly Facemark: FacemarkHostType;
  readonly FacemarkAAM: FacemarkAAMHostType;
  readonly FacemarkLBF: FacemarkLBFHostType;
  readonly FisherFaceRecognizer: FisherFaceRecognizerHostType;
  readonly LBPHFaceRecognizer: LBPHFaceRecognizerHostType;
};

type OpenCvSharpRoot_Features2D = PropertyBag & {
  readonly SIFT: SIFTHostType;
};

type OpenCvSharpRoot_Flann = PropertyBag & {
  readonly AutotunedIndexParams: AutotunedIndexParamsHostType;
  readonly CompositeIndexParams: CompositeIndexParamsHostType;
  readonly FlannCentersInit: FlannCentersInitHostType;
  readonly FlannDistance: FlannDistanceHostType;
  readonly Index: IndexHostType;
  readonly IndexParams: IndexParamsHostType;
  readonly KDTreeIndexParams: KDTreeIndexParamsHostType;
  readonly KMeansIndexParams: KMeansIndexParamsHostType;
  readonly LinearIndexParams: LinearIndexParamsHostType;
  readonly LshIndexParams: LshIndexParamsHostType;
  readonly SavedIndexParams: SavedIndexParamsHostType;
  readonly SearchParams: SearchParamsHostType;
};

type OpenCvSharpRoot_ImgHash = PropertyBag & {
  readonly AverageHash: AverageHashHostType;
  readonly BlockMeanHash: BlockMeanHashHostType;
  readonly BlockMeanHashMode: BlockMeanHashModeHostType;
  readonly ColorMomentHash: ColorMomentHashHostType;
  readonly ImgHashBase: ImgHashBaseHostType;
  readonly MarrHildrethHash: MarrHildrethHashHostType;
  readonly PHash: PHashHostType;
  readonly RadialVarianceHash: RadialVarianceHashHostType;
};

type OpenCvSharpRoot_Internal = PropertyBag & {
  readonly Util: OpenCvSharpRoot_Internal_Util;
  readonly Vectors: OpenCvSharpRoot_Internal_Vectors;
  readonly ExceptionHandler: ExceptionHandlerHostType;
  readonly ExceptionStatus: ExceptionStatusHostType;
  readonly NativeMethods: NativeMethodsHostType;
  readonly StdString: StdStringHostType;
  readonly Win32Api: Win32ApiHostType;
  readonly WindowsLibraryLoader: WindowsLibraryLoaderHostType;
};

type OpenCvSharpRoot_Internal_Util = PropertyBag & {
  readonly ArrayAddress1: ArrayAddress1HostType<any>;
  readonly ArrayAddress2: ArrayAddress2HostType<any>;
  readonly PInvokeHelper: PInvokeHelperHostType;
  readonly ReadOnlyArray2D: ReadOnlyArray2DHostType<any>;
  readonly SaturateCast: SaturateCastHostType;
  readonly ScopedGCHandle: ScopedGCHandleHostType;
};

type OpenCvSharpRoot_Internal_Vectors = PropertyBag & {
  readonly IStdVector: IStdVectorHostType<any>;
  readonly VectorOfByte: VectorOfByteHostType;
  readonly VectorOfDMatch: VectorOfDMatchHostType;
  readonly VectorOfDTreesNode: VectorOfDTreesNodeHostType;
  readonly VectorOfDouble: VectorOfDoubleHostType;
  readonly VectorOfFloat: VectorOfFloatHostType;
  readonly VectorOfImageFeatures: VectorOfImageFeaturesHostType;
  readonly VectorOfInt32: VectorOfInt32HostType;
  readonly VectorOfKeyPoint: VectorOfKeyPointHostType;
  readonly VectorOfMat: VectorOfMatHostType;
  readonly VectorOfPoint: VectorOfPointHostType;
  readonly VectorOfPoint2d: VectorOfPoint2dHostType;
  readonly VectorOfPoint2f: VectorOfPoint2fHostType;
  readonly VectorOfPoint3f: VectorOfPoint3fHostType;
  readonly VectorOfRect: VectorOfRectHostType;
  readonly VectorOfRect2d: VectorOfRect2dHostType;
  readonly VectorOfRotatedRect: VectorOfRotatedRectHostType;
  readonly VectorOfString: VectorOfStringHostType;
  readonly VectorOfVec2f: VectorOfVec2fHostType;
  readonly VectorOfVec3f: VectorOfVec3fHostType;
  readonly VectorOfVec4f: VectorOfVec4fHostType;
  readonly VectorOfVec4i: VectorOfVec4iHostType;
  readonly VectorOfVectorByte: VectorOfVectorByteHostType;
  readonly VectorOfVectorDMatch: VectorOfVectorDMatchHostType;
  readonly VectorOfVectorDouble: VectorOfVectorDoubleHostType;
  readonly VectorOfVectorInt32: VectorOfVectorInt32HostType;
  readonly VectorOfVectorKeyPoint: VectorOfVectorKeyPointHostType;
  readonly VectorOfVectorPoint: VectorOfVectorPointHostType;
  readonly VectorOfVectorPoint2f: VectorOfVectorPoint2fHostType;
};

type OpenCvSharpRoot_LineDescriptor = PropertyBag & {
  readonly KeyLine: KeyLineHostType;
  readonly LSDParam: LSDParamHostType;
};

type OpenCvSharpRoot_ML = PropertyBag & {
  readonly ANN_MLP: ANN_MLPHostType;
  readonly Boost: BoostHostType;
  readonly DTrees: DTreesHostType;
  readonly KNearest: KNearestHostType;
  readonly LogisticRegression: LogisticRegressionHostType;
  readonly NormalBayesClassifier: NormalBayesClassifierHostType;
  readonly ParamGrid: ParamGridHostType;
  readonly RTrees: RTreesHostType;
  readonly SVM: SVMHostType;
  readonly SampleTypes: SampleTypesHostType;
  readonly StatModel: StatModelHostType;
  readonly TrainData: TrainDataHostType;
};

type OpenCvSharpRoot_OptFlow = PropertyBag & {
  readonly CvOptFlow: CvOptFlowHostType;
};

type OpenCvSharpRoot_Quality = PropertyBag & {
  readonly QualityBRISQUE: QualityBRISQUEHostType;
  readonly QualityBase: QualityBaseHostType;
  readonly QualityGMSD: QualityGMSDHostType;
  readonly QualityMSE: QualityMSEHostType;
  readonly QualityPSNR: QualityPSNRHostType;
  readonly QualitySSIM: QualitySSIMHostType;
};

type OpenCvSharpRoot_Segmentation = PropertyBag & {
  readonly IntelligentScissorsMB: IntelligentScissorsMBHostType;
};

type OpenCvSharpRoot_Text = PropertyBag & {
  readonly BaseOCR: BaseOCRHostType;
  readonly ComponentLevels: ComponentLevelsHostType;
  readonly CvText: CvTextHostType;
  readonly OCRTesseract: OCRTesseractHostType;
};

type OpenCvSharpRoot_Tracking = PropertyBag & {
  readonly TrackerCSRT: TrackerCSRTHostType;
  readonly TrackerKCF: TrackerKCFHostType;
  readonly TrackerTypes: TrackerTypesHostType;
};

type OpenCvSharpRoot_XFeatures2D = PropertyBag & {
  readonly BriefDescriptorExtractor: BriefDescriptorExtractorHostType;
  readonly FREAK: FREAKHostType;
  readonly LATCH: LATCHHostType;
  readonly LUCID: LUCIDHostType;
  readonly SURF: SURFHostType;
  readonly StarDetector: StarDetectorHostType;
};

type OpenCvSharpRoot_XImgProc = PropertyBag & {
  readonly Segmentation: OpenCvSharpRoot_XImgProc_Segmentation;
  readonly AdaptiveManifoldFilter: AdaptiveManifoldFilterHostType;
  readonly AngleRangeOption: AngleRangeOptionHostType;
  readonly CvXImgProc: CvXImgProcHostType;
  readonly DTFilter: DTFilterHostType;
  readonly EdgeAwareFiltersList: EdgeAwareFiltersListHostType;
  readonly EdgeBoxes: EdgeBoxesHostType;
  readonly FastBilateralSolverFilter: FastBilateralSolverFilterHostType;
  readonly FastGlobalSmootherFilter: FastGlobalSmootherFilterHostType;
  readonly FastLineDetector: FastLineDetectorHostType;
  readonly GuidedFilter: GuidedFilterHostType;
  readonly HoughDeskewOption: HoughDeskewOptionHostType;
  readonly HoughOP: HoughOPHostType;
  readonly LocalBinarizationMethods: LocalBinarizationMethodsHostType;
  readonly RFFeatureGetter: RFFeatureGetterHostType;
  readonly RulesOption: RulesOptionHostType;
  readonly SLICType: SLICTypeHostType;
  readonly StructuredEdgeDetection: StructuredEdgeDetectionHostType;
  readonly SuperpixelLSC: SuperpixelLSCHostType;
  readonly SuperpixelSEEDS: SuperpixelSEEDSHostType;
  readonly SuperpixelSLIC: SuperpixelSLICHostType;
  readonly ThinningTypes: ThinningTypesHostType;
  readonly WMFWeightType: WMFWeightTypeHostType;
};

type OpenCvSharpRoot_XImgProc_Segmentation = PropertyBag & {
  readonly GraphSegmentation: GraphSegmentationHostType;
  readonly SelectiveSearchSegmentation: SelectiveSearchSegmentationHostType;
  readonly SelectiveSearchSegmentationStrategy: SelectiveSearchSegmentationStrategyHostType;
  readonly SelectiveSearchSegmentationStrategyColor: SelectiveSearchSegmentationStrategyColorHostType;
  readonly SelectiveSearchSegmentationStrategyFill: SelectiveSearchSegmentationStrategyFillHostType;
  readonly SelectiveSearchSegmentationStrategyMultiple: SelectiveSearchSegmentationStrategyMultipleHostType;
  readonly SelectiveSearchSegmentationStrategySize: SelectiveSearchSegmentationStrategySizeHostType;
  readonly SelectiveSearchSegmentationStrategyTexture: SelectiveSearchSegmentationStrategyTextureHostType;
};

type OpenCvSharpRoot_XPhoto = PropertyBag & {
  readonly Bm3dSteps: Bm3dStepsHostType;
  readonly CvXPhoto: CvXPhotoHostType;
  readonly GrayworldWB: GrayworldWBHostType;
  readonly InpaintTypes: InpaintTypesHostType;
  readonly LearningBasedWB: LearningBasedWBHostType;
  readonly SimpleWB: SimpleWBHostType;
  readonly TonemapDurand: TonemapDurandHostType;
  readonly TransformTypes: TransformTypesHostType;
  readonly WhiteBalancer: WhiteBalancerHostType;
};

declare global {
  /**
   * OpenCvSharp 类型集合宿主对象
   * @since 0.50.0
   */
  const OpenCvSharp: OpenCvSharpCollection;
}

export {};
